wolfi-dev/wolfictl

pkg/advisory/advisory.go
Signed-off-by: Dan Luhring <dluhring@chainguard.dev>
=> Fix doc comment glitch from automatic lint fixes

pkg/cli/advisory_sync_secfixes.go
=> Offer hint for syncing secfixes on warning

.github/actions/action.yaml
Signed-off-by: James Rawlings <jrawlings@chainguard.dev>
=> clean cloned path from the correct folder

go.mod, go.sum
Updating the melange dependency to pull in the newly minted ruby pipelines
=> Update melange dependency to match HEAD

pkg/advisory/advisory.go
Previously, `wolfictl advisory discover` would possibly modify a package config file if there were one or more matches returned by the `VulnerabiltySearcher` for the package **but no matches ended up requiring substantive data changes** (e.g. no new matches). This caused confusion and excess noise in git diffs.
This PR adjusts the behavior to explicitly skip writing changes to the config unless there's a net new advisory to record for the package.
=> Don't modify file advisories if no new vulnerability matches apply to the package

docs/pod.md
Copied out from https://github.com/wolfi-dev/dag/blob/main/k8s.md which I intend to archive soon (https://github.com/wolfi-dev/dag/pull/45)
=> add docs for k8s pod creation

pkg/checks/update.go, pkg/update/githubReleases.go, pkg/update/releaseMonitor.go
tidying up a few things after using the `wolfictl check update` in practice.
=> wolfi update: remove unnecessary code, add some comments and continue loop if melange bump fails

go.mod, go.sum, pkg/update/package.go, pkg/update/releaseMonitor.go, pkg/update/update.go
issues contain the error "git push: object not found"
example: https://github.com/wolfi-dev/os/issues/1274
=> wolfi update: rework switching branches as we are seeing issues created on wolfi

pkg/update/update.go
To be clear I really dislike this but I've not once been able to reproduce the `failed to propose changes` errors we get on wolfi.  So adding a bunch of logging and even a sleep as a way to gather more info.
=> wolfictl update: add extra debug logging to help investigate #197

pkg/cli/pod.go
=> Make APKINDEX public on upload

go.mod, go.sum
Especially to pick up the change from https://github.com/chainguard-dev/yam/pull/16
=> Bump version of yam

pkg/configs/advisory/advisory.go, pkg/configs/advisory/section_updaters.go
Fail fast when seeing the secfixes field.
=> Error on unknown secfixes field

pkg/dag/graph.go
When resolving packages, we looked up the keys each time. Every single one, without any caching. This is different than the repos themselves, where we kept a cache. We already cache the repo indexes correctly.
I profiled a run before and after. Admittedly, just one run each, so hardly statistically solid, but the pre-run had ~480s and the post-run had ~260s. I will take the gain.
cc @kaniini who pointed out the issue (thanks) and @jonjohnsonjr (who pointed out a bunch more on their way)
=> cache key lookups

scripts/setup-cluster.sh
Blocked on https://github.com/wolfi-dev/os/pull/2514
=> remove 'kubectl set image' from setup-cluster.sh

pkg/dag/graph.go
This cuts NewGraph in half for me (12s -> 6s).
Before we call AddEdge, we always call CreatesCycle.
The first thing that AddEdge does is call CreatesCycle, which is currently 99% of the execution time of AddEdge.
Instead of calling that twice for every edge, just call AddEdge and check to see if it would have created a cycle.
Because we very rarely hit cycles, 99% of the time, this is just duplicated work.
=> Don't explicitly check CreatesCycle

go.mod, go.sum
@jonjohnsonjr (aka "the performance wizard" 🧙‍♂️ ) updated the underlying 3rd-party graph algorithm so it is _massively_ faster.
The entire graph now runs in 37s instead of 4-6 mins!!
=> use jonjohnson rocket graph optimizations

pkg/dag/packages.go
We were spending a lot of time in fmt.Sprintf and copying these packages around.
=> Speed up dag.NewGraph a bit

go.mod, go.sum
This picks up a handful of performance optimizations.
Before:
wolfictl text  36.99s user 4.81s system 220% cpu 18.956 total
After:
wolfictl text  1.97s user 3.10s system 97% cpu 5.171 total
=> Bump github.com/dominikbraun/graph

pkg/dag/graph.go
In wolfi, we do not allow ap package to satisfy its own dependency at _build time_. We do, however, allow it for runtime. For example, [openjdk-11.yaml](https://github.com/wolfi-dev/os/blob/main/openjdk-11.yaml#L8-L12) depends at runtime on `openjdk-11-jre`, which is a subpackage of `openjdk-11`, and this is fine:
```yaml
package:
name: openjdk-11
version: 11.0.20.4
epoch: 1
description:
copyright:
- license: GPL-2.0-only
dependencies:
runtime:
- openjdk-11-jre
- freetype
- fontconfig
```
However, the graph code did not allow a "satisfy my own dependency ever". This PR updates it to allow it for runtime, but not for build time (as before).
=> optionally handle self as dependency

pkg/dag/graph.go, pkg/dag/graph_test.go, pkg/dag/testdata/basic/busybox.yaml
This resolves an issue wherein we would resolve a cycle by using a higher-level resolver, rather than the original one that was used for it.
With this in place, the graph actually works!
=> pass resolver along with edges

pkg/cli/scan.go
Example:
```console
$ go run . scan ~/code/wolfi-os/packages/aarch64/gradle-8-8.2.0-r0.apk --require-zero
gradle-8-8.2.0-r0.apk
├── 📄 /usr/share/java/gradle/lib/guava-31.1-jre.jar
│       📦 guava 31.1-jre (java-archive)
│           Medium CVE-2023-2976 GHSA-7g45-4rm6-3mm3 fixed in 32.0.0
│
├── 📄 /usr/share/java/gradle/lib/h2-2.1.214.jar
│       📦 h2 2.1.214 (java-archive)
│           High CVE-2022-45868 GHSA-22wj-vf5f-wrvj fixed in 2.2.220
│
└── 📄 /usr/share/java/gradle/lib/plugins/ivy-2.3.0.jar
📦 ivy 2.3.0 (java-archive)
High CVE-2022-37866 GHSA-wv7w-rj2x-556x fixed in 2.5.1
FATA[0003] error during command execution: more than 0 vulnerabilities found 
exit status 1
```
=> Add flag for requiring zero vulnerabilities

pkg/cli/scan.go
=> scan: add support for JSON output

pkg/cli/scan.go, pkg/scan/apk.go
The main feature of this PR is to allow SBOMs of APKs — generated via `wolfictl sbom <apk-file> -o syft-json` — to be used as the input to `wolfictl scan`, via the new `-s`/`--sbom` flag on `wolfictl scan`.
This means that we can now use the "first-class SBOMs" workflow, where we generate an APK's SBOM just once, and can scan that _SBOM_ (as a proxy for the original APK!) as often as we'd like.
Demo:
```console
$ pwd
/Users/dan/code/wolfi-os
$ wolfictl scan ./packages/aarch64/gradle-8-8.2.0-r0.apk
Will process: gradle-8-8.2.0-r0.apk
├── 📄 /usr/share/java/gradle/lib/guava-31.1-jre.jar
│       📦 guava 31.1-jre (java-archive)
│           Medium CVE-2023-2976 GHSA-7g45-4rm6-3mm3 fixed in 32.0.0
│
├── 📄 /usr/share/java/gradle/lib/h2-2.1.214.jar
│       📦 h2 2.1.214 (java-archive)
│ …
```
=> scan: add support for scanning an APK's SBOM

pkg/sbom/pkginfo.go
Sometimes apk's include a `builddate` field in their `PKGINFO` data. Before, wolfictl's sbom functionality printed a warning about this:
```console
$ wolfictl scan packages/aarch64/aws-load-balancer-controller-2.4.5-2.4.5-r2.apk
Will process: aws-load-balancer-controller-2.4.5-2.4.5-r2.apk
Unknown key: builddate
```
This PR stops printing messages about unknown fields; and, it accounts for parsing the `builddate` field data.
A great next step here would be to incorporate an upstream APK parsing function such as [this](https://gitlab.alpinelinux.org/alpine/go/-/blob/master/repository/package.go#L49). There's a new TODO in the code for this.
cc: @mattmoor
=> fix: recognize builddate field and ignore unknown fields

pkg/cli/pod.go
Got carried away while adding error context.
=> Actually check if err == nil in pod

docs/check_so_name.md, pkg/checks/diff.go, pkg/checks/so_name.go, pkg/update/githubReleases.go
I found some typos in our code.
=> chore: fix some typos in the code

pkg/scan/apk.go
The `grype.DefaultVulnerabilityMatcher` construction is not the default used in Grype, funny enough! This PR adjusts the `VulnerabilityMatcher`'s `Matchers` to behave more like Grype today, particularly by enabling CPE matching in cases where it otherwise defaults to being turned off.
=> fix: configure matchers more like Grype

pkg/cli/dot.go
Calling this a few thousand times generates a lot of GC pressure. This is ~5x faster than before in my local testing.
Related https://github.com/wolfi-dev/wolfictl/issues/344
=> Reuse adjacency map

go.mod, go.sum
Bump melange dependency so that CI gains access to the latest pipelines added.
=> feat: bump melange dependency for latest features

pkg/advisory/discover.go, pkg/cli/advisory_discover.go, pkg/vuln/nvdapi/detector.go
- avoid hard fail when NVD rate limits
- add missing vulnerability warning when new vulns found
- minor doc and variable name fixes
=> fix: minor tweaks to adv discover

go.mod, go.sum, pkg/cli/dot.go
This is a scrappy little web app for exploring the build graph.
=> Add wolfictl dot --web

pkg/cli/dot.go
Using -S will only include one incoming edge to each node giving a subgraph that spans every node but isn't impossible to understand.
Using -R will recursively walk the deps and render the whole graph.
I would not recommend using -R without -S.
=> Add -S and -R to wolfictl dot

pkg/cli/build.go, pkg/cli/pod.go, pkg/cli/text.go, pkg/dag/packages.go
`SubgraphWith{Leaves,Roots}` doesn't seem to work, and aren't effectively called by anything today anyway. Remove those calls while Jon fixes the methods, and we can readd them.
=> don't call subgraph methods, they're broken

pkg/cli/text.go
We previously ignored subpackages because we can't build them separately from their containing package, but filtering out subpackages means that the dependency graph is incomplete.
Instead of filtering them out before calling the toposort, we just omit subpackages when we emit the build order. Given that subpackages always depend on their parents, the toposort will still be valid.
Before this change, the first package was "wget", which has a dependency on "openssl-dev", which doesn't exist in the stage3 bootstrap repo.
After this change, the first package is "openssl", which seems correct.
=> Consider subpackage dependencies in wolfictl text

pkg/cli/build.go
this might also warrant just putting into melange. let me know if we prefer doing it that way
ref: https://github.com/wolfi-dev/os/blob/main/Makefile#L71
fixes: https://github.com/wolfi-dev/os/actions/runs/6163125847/job/16726015131
=> ensure sourcedir exists before building

pkg/cli/build.go
plumb this through like we do in melange. use it for saving build logs and uploading them in CI
=> plumb the log-policy through the cli to the build

pkg/cli/build.go
Semi reverts #398 (merged a little too quickly, my fault!) in favor of `log-dir`.
This feels a little nicer to use since specifying `--log-policy` is really designed for individual apk builds, where `wolfictl build` needs to worry about batch builds.
This changes the default behavior, and doesn't require a change to https://github.com/wolfi-dev/os/blob/409fee886aeab35be3a48356a62bd6fccbe1820b/.github/workflows/build-world.yaml#L47
=> change log-policy to log-dir for better ux

pkg/checks/diff.go
This is actually a super interesting file for diffs because it tells us if the dependency graph has changed.
(I am assuming that `diff.log` format is for humans and not being parsed by anything other than the markdown renderer, but let me know if this could possibly break things.)
Sample output for `google-cloud-sdk` I happen to have sitting around:
```
<details>
<summary>Package google-cloud-sdk: Click to expand/collapse</summary>
Package google-cloud-sdk:
.PKGINFO:
(
"""
... // 2 identical lines
pkgver = 427.0.0-r1
arch = aarch64
- 	size = 300234178
+ 	size = 262017691
origin = google-cloud-sdk
pkgdesc = Google Cloud Command Line Interface
url = 
- 	commit = ae4a1c8d7e1a54475ff3de9fbcb7380db6e8c6b2
- 	builddate = 1695065068
+ 	commit = 22be17a6acdeac69acbfccc5eca43a00eac6886d
license = …
```
=> Don't skip .PKGINFO in diff check

pkg/cli/build.go, pkg/cli/dot.go, pkg/cli/text.go
This is an annoying stumbling block I always forget, let's just default to the sane default.
=> use wolfi repos by default

pkg/cli/build.go, pkg/cli/text.go
=> fix default repository-append

pkg/lint/linter.go, pkg/lint/rules.go
We don't require this in any repo anymore, so let's just drop it.
=> drop lint rule for makefile line

pkg/advisory/alias_finder.go
In the [PR that originally introduced vulnerability alias discovery](https://github.com/wolfi-dev/wolfictl/pull/419), a noted "future work" item was to cache results from lookups of CVE and GHSA IDs using the GitHub API.
This PR introduces a simple in-memory caching mechanism to avoid redundant calls to the GitHub API.
**Sample runs of alias discovery for a distro:**
Before:
```
wolfictl adv alias discover  2.10s user 0.91s system 5% cpu 56.769 total
```
After:
```
wolfictl adv alias discover  1.45s user 0.36s system 11% cpu 15.502 total
```
=> perf: cache results for GHSA queries

pkg/cli/advisory_create.go
This makes a small addition in the `wolfictl adv create` command, where after creation succeeds, a follow-up pass takes place to discover any new aliases for that new advisory and any other advisories in the same document.
=> feat: alias discovery on advisory creation

pkg/update/githubReleases.go, pkg/update/githubReleases_test.go
Fixes: #468 
/cc @rawlingsj @ajayk
=> Use `REGEX` instead of `strings.Containes` to match  `tag-filter`

pkg/update/githubReleases.go, pkg/update/githubReleases_test.go
Reverts wolfi-dev/wolfictl#469
=> Revert "Use `REGEX` instead of `strings.Containes` to match  `tag-filter`"

pkg/update/githubReleases.go, pkg/update/githubReleases_test.go
Reverts wolfi-dev/wolfictl#458
=> Revert "wolfi bot: we now have ignore-regex update config so removing bad ove…"

pkg/update/releaseMonitor.go
Ignore regex fails on the release monitor https://github.com/wolfi-dev/os/pull/8058/
=> fix: ignore regex is not working for release monitor

go.mod, pkg/scan/apk.go
this adds the grype db information to the results
=> add grype db information in the scanning results

pkg/cli/scan.go, pkg/scan/apk.go
We were spending most of our time hashing the grype DB instead of scanning things. This introduces a scan.Scanner to hold the cached DB so we spend (a lot) more time scanning.
Fixes https://github.com/wolfi-dev/wolfictl/issues/520
=> Cache grype DB initialization across scans

pkg/configs/build/section_updaters.go
somehow I missed this one too.
=> fix: updater for environment

pkg/git/git.go
(reason explained in code comment)
=> fix: no git auth if no token available

go.mod, pkg/cli/build.go, pkg/cli/commands.go, pkg/cli/lint.go, pkg/lint/linter.go, pkg/lint/options.go, pkg/lint/rules.go
```
go run ./ lint ../wolfi-os 2>&1 | grep "not valid SPDX" | wc -l
177
```
very cool 😭
=> lint: warn on invalid licenses

pkg/update/deps/cleanup.go, pkg/update/deps/cleanup_test.go, pkg/update/deps/testdata/config-10.yaml, pkg/update/deps/testdata/config-10_expected.yaml
related to this issue https://github.com/wolfi-dev/os/actions/runs/7726478907/job/21062833724#step:5:30259
=> fix: bug when iterating a pipeline with deleted items

pkg/cli/build.go
We weren't cancelling the right context to actually send a finish signal, so it was impossible for wolfictl build to exit.
=> Fix done signalling in wolfictl build

pkg/advisory/alias_finder.go
we need to use this for the cve automation, where we have a token per request, we cannot add that as env var because other requests will have their own token, and to avoid the env var being replaced
=> add way to pass a github token instead of using env var

pkg/cli/build.go
Similar to https://github.com/chainguard-dev/melange/pull/1025
=> omit arch log key when building one arch

docs/advisory_guide_flow.md, go.mod, go.sum, pkg/apk/apk.go, pkg/cli/advisory.go, pkg/cli/advisory_guide.go, pkg/cli/components/breather/breather.go, pkg/cli/components/ctrlcwrapper/ctrlcwrapper.go, pkg/cli/components/keytocontinue/key_to_continue.go, pkg/cli/components/picker/picker.go, pkg/cli/internal/builds/builds.go, pkg/cli/internal/wrapped/wrapped.go, pkg/distro/detect.go, pkg/sbom/cache.go, pkg/scan/apk.go
This introduces a new command: `wolfictl adv guide`. This command is a new approach to responding to vulnerabilities in our distro packages by entering the appropriate advisory data.
This is a work in progress!
=> feat(adv): interactive guide for advisory entry

pkg/dag/packages.go
This is polluting wolfictl build logs.
=> Use clog over log

pkg/cli/build.go
This approximates what we do in the Makefile instead of streaming everything to stderr.
=> build: Write logs to files instead of stderr

pkg/cli/build.go
This makes wolfictl build work as a replacement for "make package/foo".
I've also dropped an errgroup we use for building every arch simultaneously. I think it kind of betrays the -j flag a bit, and doing that made it easier to add the per-arch logfile to the error message that gets returned.
=> build: Support passing packages as argv

pkg/scan/apk.go
This way it can be reused elsewhere!
=> make NewGrypeVulnerabilityMatcher function public

pkg/cli/build.go
This also puts the global config in a single struct so we can differentiate between task-level fields and global values.
=> build: Host some hard-coded values up into flags

pkg/cli/build.go
This allows things later in the graph to depend on things that get built earlier in the graph (which brings us closer to bootstrap).
Also fix a couple annoyances I discovered around reporting status.
=> Regen APKINDEX after each package builds

pkg/cli/build.go
We used to do something like this:
```
for pkg in packages():
for arch in archs:
build(pkg, arch)
```
This change looks more like this:
```
for arch in archs:
for pkg in packages(arch):
build(pkg, arch)
```
This works a little bit better because the dependency graph only makes sense within a given arch; e.g. we shouldn't wait for aarch64/go to finish before building x86_64/crane.
This also tees us up to prune the set of packages we need to build based on an existing APKINDEX.
=> build: Group by arch

pkg/cli/build.go
Melange uses this error to communicate that an arch should be skipped. Currently, we fail if we hit this, but we shouldn't.
=> build: skip arch on sentinel error

pkg/cli/build.go
This defaults to false to match how melange works.
=> build: Add --generate-index flag

pkg/cli/build.go
Builds logs were remarkably noisy, this quiets things down quite a bit.
=> build: Log less when we don't do things

pkg/cli/build.go, pkg/dag/packages.go
Also use the right filename for melange yaml files in subdirectories instead of hardcoding them.
=> Skip packages for different arch

pkg/cli/build.go
This optional flag uses the destination APKINDEX to check if packages already exist before attempting to Stat() the APK. This saves us time is Stat() is expensive e.g. for gcsfuse.
=> build: Add destination repo

pkg/cli/build.go
This groups via the logfile name and only logs failed builds, so it shouldn't be too noisy.
=> build: Write failed build logs to stdout

pkg/cli/build.go
In a previous episode, we did each arch as a separate graph: 34661bf97929b7f7232ad54dcb3eb38d722f400e
This is fine for building them independently and joining together at the end, but if we want to update the APKINDEX between builds, this makes things more difficult, so we effectively undo that change in preparation for pulling the APKINDEX updates into wolfictl build.
=> build: Un-group by arch

pkg/cli/build.go
Reverts wolfi-dev/wolfictl#704
=> Revert "build: Un-group by arch"

pkg/cli/build.go
Previously we would return early on a per-arch basis and skip generating
the index, but I overlooked that path when splitting the per-arch builds
into a separate method from index generation.
=> Skip regenerating index if we skip all archs

pkg/cli/build.go
This got lost in a large refactor.
=> build: Fix --destination-repository

go.mod, go.sum
https://github.com/chainguard-dev/go-apk/pull/229
=> Bump go-apk to pick up better index errors

pkg/cli/build.go
Instead of skipping the whole thing and only indexing/updating orphaned APKs at the end, we will adopt any built-but-not-indexed APKs into our local APKINDEX so that we can use them in the current build.
This will allow us to recover in the case where only certain packages succeed to build (due to cyclical dependencies or otherwise) for new packages where we can't fall back to a previous version.
```
$ wolfictl bump crane && wolfictl build --arch aarch64 crane
$ wolfictl build --dry-run --destination-repository https://packages.wolfi.dev/os crane
2024/03/30 15:40:56 INFO DRYRUN: would have built packages/x86_64/crane-0.19.1-r3.apk
2024/03/30 15:40:56 INFO Generating apk index from packages in packages/x86_64
2024/03/30 15:40:56 INFO DRYRUN: would have indexed …
```
=> Index APKs if they are already built

pkg/distro/detect.go, pkg/distro/detect_test.go, pkg/distro/distro.go
in preparation for the new advisories repo for extra packages
=> add extra packages distro

pkg/cli/test.go
addresses some of the nits in #743
=> clean up testing logic a bit

pkg/apk/apk.go
Fixing the code fetching the latest package version in a different place. There is already a test validating this function.
=> fix: get latest package version

pkg/cli/bump.go, pkg/cli/check_update.go, pkg/cli/vex.go, pkg/cli/withdraw.go
The previous usage statement just showed:
wolfictl check update [flags]
Which did not make it obvious that you could pass a melange .yaml file in.
=> Improve 'wolfictl check update' usage to include yaml.

pkg/internal/bundle/bundle.go
also lowercase for packages like https://github.com/wolfi-dev/os/blob/main/R.yaml
=> use shorter pod name

pkg/cli/build.go
We aren't doing anything with this other than checking hashes, so don't keep the files around.
=> build: Discard bundle output for now

pkg/cli/bundle.go
Avoid racing to push base layers and act more like wolfictl build for parallelism.
=> bundle: Generate bundles faster

pkg/cli/build.go, pkg/internal/bundle/bundle.go
this add 3 flags that makes the corresponding k8s properties configurable
the machine family affinity allows us to more easily try out different machine types for amd64 builds
arm64 builds are coupled to t2a
namespace and service account defaults to the current "default"
allow it to be changed so we can run in different namespace and with different service account
=> elastic: allow namespace, service account and machine family affinity configurable

pkg/cli/build.go, pkg/cli/bundle.go
Also downgrade some logs from Infof to Debugf.
=> build: Add bundle spans

pkg/cli/build.go, pkg/cli/bundle.go, pkg/internal/bundle/bundle.go
Instead of a separate "melange bundle" for each build, just have a single image where the specific build gets supplied via podspec args.
This cuts down on bundle creation/push time dramatically.
=> bundle: Simplify bundle topology

pkg/cli/build.go
The APKINDEX generation stuff logs a lot more than we care to see, so quiet that down.
Also log pod phase transitions so we can get some kind of update on their status as things progress.
Also include the pod status message when the pod fails, so we log something more useful than "pod failed".
Looks something like this now:
```
2024/05/24 21:23:59 INFO creating pod for openssl-3.3.0-r7
2024/05/24 21:23:59 INFO creating pod for openssl-3.3.0-r7
2024/05/24 21:24:00 INFO pod openssl-amd64-lxtn5 phase changed: Unknown -> Pending
2024/05/24 21:24:00 INFO pod openssl-arm64-76j9r phase changed: Unknown -> Pending
2024/05/24 21:24:40 INFO pod openssl-amd64-lxtn5 phase changed: Pending -> Running
2024/05/24 21:24:40 INFO pod openssl-arm64-76j9r phase changed: Pending -> Running
2024/05/24 21:27:20 …
```
=> bundles: Log fewer, more useful lines

pkg/cli/build.go
Instead of rate limiting both the APK upload and the APKINDEX upload, just rate limit the APKINDEX upload and retry any APK uploads a single time.
=> build: Retry GCS uploads once

pkg/cli/build.go
Since we're taking out a lock to update the index, we should move the APK uploading outside of that locked section.
=> bundles: Split APK upload from indexing

pkg/cli/build.go
=> bundles: Fix retrying GCS error

pkg/cli/build.go
By default, the storage client will only retry idempotent operations:
https://github.com/googleapis/google-cloud-go/blob/704c78aeb1c14d374cff501445b0878aafa22b91/storage/http_client.go#L970-L977
Uploading an object is only idempotent when using conditional requests:
https://github.com/googleapis/google-cloud-go/blob/704c78aeb1c14d374cff501445b0878aafa22b91/storage/writer.go#L185
Since these objects should only be uploaded once and never updated, we can use the DoesNotExist condition to pass the idempotency check.
=> bundles: Make write finalization idempotent

pkg/cli/build.go, pkg/cli/bundle.go
See https://github.com/chainguard-dev/melange/issues/1236
=> Dedupe subpackages

pkg/cli/build.go
This will be nicer than grepping through logs to figure out what failed.
Noticed one ~issue where existing destination-bucket APKINDEX wasn't being considered for skipping builds, which doesn't matter that much other than making the report ~inaccurate, so I fixed it.
=> bundles: Add --summary output for builds

pkg/cli/bundle.go
Melange uses these to determine the commit for .PKGINFO, so we just include those files in the bundle. We may want to propagate that via a flag or something in the future, but this is the simplest way to get parity with our current process.
=> bundles: Embed .git/HEAD and .git/refs/heads

pkg/cli/build.go
We want to retry 429s automatically, but that's not generally safe for writes. This tracks the object generation client-side so that we can set IfGenerationMatch conditions.
=> bundles: Track generations for APKINDEX objects

pkg/cli/apk.go
This incorporates `apkrane ls` to list packages in a repo, optionally in JSON and optionally only latest packages, etc.
This supports HTTP_AUTH, local and stdin indexes.
=> apk ls: list repository packages

pkg/cli/bundle.go
This only seems to reproduce in GHA, which is very unfortunate to debug.
=> bundles: Add more logging to getEpochs

pkg/cli/advisory_list.go
* Add new `--type` filtering flag
* Redesign output into colored table
* Hyperlink CVE and GHSA IDs
* Remove distro auto-detection
=> feat(adv): `ls` command enhancements

pkg/advisory/export.go, pkg/cli/advisory_list.go
New flag for `wolfictl adv ls`: Now we can examine particular component types, like `python`, `go-module`, `apk`, etc. (Today these come from Syft.)
=> feat(adv/ls): filter by detected component type

pkg/cli/advisory_list.go
Adds flags to `adv ls` to let the user filter advisories based on whether an advisory was created/updated after/before a specified date.
=> feat(adv): date-based filtering for `ls`

pkg/cli/build.go, pkg/cli/bundle.go
...Also teach `wolfictl build` about `HTTP_AUTH`
=> bundle: export more fields and structs, so we can use them outside

pkg/cli/advisory_list.go
Adds a new `--count` flag to `wolfictl adv ls`, which returns a count of the advisories matching the query, rather than showing those advisories themselves.
E.g.
=> feat(adv/ls): flag to get count from query

pkg/private/bundle/bundle.go
Needs a tool rebuild + digest update
Ref: https://github.com/chainguard-dev/infra-images/pull/1206
=> build: use gvisor node selector too

pkg/advisory/discover.go
=> fix(adv/discover): panic on nonexistent package

pkg/cli/apk.go
\# of latest packages built in the last 2 weeks:
```
$ go run ./ apk ls https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz --latest --newer-than 336h | wc -l
1783
```
vs last 24 hours:
```
$ go run ./ apk ls https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz --latest --newer-than 24h | wc -l
49
```
This can be done with some `jq`-fu, but that's tedious and error prone.
=> apk ls --newer-than: show only packages built recently

pkg/cli/bundle.go
This allows us to attach arbitrary data to the bundle e.g. which GHA run created it.
```
$ crane manifest $BUNDLE | jq .annotations
{
"foo": "bar",
"hi": "kenny"
}
```
=> bundle: Add --annotation flag

pkg/cli/build.go
fix: https://github.com/wolfi-dev/wolfictl/issues/1018
=> return error only when its non-nil for walk

pkg/cli/build.go
This makes everything messy and makes it difficult to see the overall waterfall.
=> build: Remove start and waiting info from traces

pkg/cli/build.go, pkg/cli/bundle.go
also have bundle method return digest
=> elastic: export properties from build/bundle config for reuse

pkg/cli/bundle.go
Same as https://github.com/wolfi-dev/wolfictl/pull/1055 but for --pipeline-dir.
=> Make --pipeline-dir relative

pkg/cli/build.go, pkg/cli/bundle.go
use gcrane keychain for pusher auth
=> expose build config Fuse

pkg/cli/build.go
Instead of uploading APKs and indexes to GCS, this now only supports the HTTP-based upload path, deferring the signing and indexing to our apk repo.
This simplifies a lot, especially re: locking.
=> bundles: Drop --destination-bucket

pkg/cli/build.go
Doing this for every pod is a bit wasteful.
=> bundles: Extract clientset initialization

pkg/cli/build.go
I always forget that path.Join doesn't play nicely with schemes.
=> bundle: Fix upload URL

pkg/cli/build.go
Maybe this will give the metadata server more time to come up?
=> bundles: Defer clientset initialization

pkg/checks/diff.go
Adds basic syntax highlighting for diffs.
=> diff: Use diff markdown fence.

go.mod, go.sum
as discussed in https://chainguard-dev.slack.com/archives/C05CM0DM7RV/p1722630377284259?thread_ts=1722593910.676959&cid=C05CM0DM7RV
=> chore: use melange main

pkg/update/deps/cleanup.go, pkg/update/deps/cleanup_test.go, pkg/update/deps/testdata/config-11.yaml, pkg/update/deps/testdata/config-11_expected.yaml
related to this error: https://github.com/wolfi-dev/os/actions/runs/10289224641/job/28476459222?pr=25816
and this discussion on Slack: https://chainguard-dev.slack.com/archives/C0627BW5GLF/p1723132481217119
=> fix: add support to clone using the branch

pkg/advisory/osv.go, pkg/cli/advisory.go, pkg/cli/advisory_osv.go
Also fix `newLogger` to use charm logging better.
Example of new logging:
=> feat(adv): add basic logging to osv data generation

pkg/advisory/testdata/validate/duplicate-advisory-by-id-across-documents/ko.advisories.yaml, pkg/advisory/testdata/validate/duplicate-advisory-by-id-across-documents/mo.advisories.yaml, pkg/advisory/testdata/validate/fixed-version/ko.advisories.yaml, pkg/advisory/testdata/validate/fixed-version/mo.advisories.yaml, pkg/advisory/validate.go, pkg/advisory/validate_test.go
Also add a test to ensure the validation works.
This does not yet support validation across multiple indices, but that can be added when needed, too.
=> feat(adv): validate adv ID uniqueness within an index

pkg/cli/advisory_copy.go
=> fix(adv/cp): new advisories need unique CGA IDs

pkg/cli/scan.go
=> scan: Set auth for remote packages sometimes

pkg/dag/graph.go
This was seemingly added to prevent accidentally having cycles in the dependency graph, but this also prevents us from retiring older versions of packages such that we only have the most recent version. This matters if, for example, we wanted to migrate to a new repository location without backfilling every package ever.
=> text: Only consider local repo for self-providers

pkg/cli/components/scanfindings/scanfindings.go, pkg/cli/styles/styles.go
=> feat(scan): colors that are legible with light background

.github/actions/action.yaml, .github/workflows/golangci-lint.yaml, Makefile, go.mod
Update workflows, and also upgrade golangci to latest.
=> go.mod: upgrade to go 1.24.0

pkg/dag/graph.go
This was just dropped by our local dag ordering logic, which meant we wouldn't pull in the right packages if we had a dependency that provided a virtual with a higher priority than other.
=> dag: Respect provider-priority

pkg/scan/apk_test.go
Requested in https://github.com/wolfi-dev/wolfictl/pull/1475\#discussion_r1978449599.
=> test(scan): shouldAllowMatch

pkg/lint/linter.go, pkg/lint/rules_test.go, pkg/lint/testdata/files/invalid-spdx-license.yaml
This fixes some issues with how wolfictl displays errors. With the changes that landed in https://github.com/wolfi-dev/actions/pull/350 my complaints about missing issues should be address but I still think these changes make sense. See the individual commits for explanations.
=> linter: fixes for printing and a new test

pkg/cli/bump.go, pkg/cli/bump_test.go
See https://github.com/wolfi-dev/os/pull/52024
=> bump: Don't fail if there are comments

pkg/scan/filter.go
This is intended to make it easier to understand what's happening when we filter the scan results for an APK using advisory data and a particular filtering strategy.
cc: @tdunlap607
=> chore(scan): debug logging for scan result filtering
