pkg/lint/rules.go, pkg/lint/rules_test.go, pkg/lint/testdata/files/forbidden-keyring.yaml, pkg/lint/testdata/files/forbidden-repository.yaml
This PR introduces 2 news lint rules with their tests:
* `forbidden-repository-used`
* `forbidden-keyring-used`
These checks are required to get rid of "legacy" [lint.sh](https://github.com/wolfi-dev/os/blob/main/lint.sh) script:
```
if grep -q packages.wolfi.dev/os $f; then
yq -i 'del(.environment.contents.repositories)' $f
yq -i 'del(.environment.contents.keyring)' $f
fi
```
Also please check: https://github.com/wolfi-dev/os/issues/86
> checked-in packages shouldn't depend on packages.wolfi.dev/os or include its keyring; packages are fetched from that repo and depended on locally during the build
Intentionally used _list_ to get better control to forbid multiple repos and keyrings (if need be)
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
=> lint: forbid rules for package and keyring

.github/actions/action.yaml
initially for faster iterations let's compile wolfictl, in the future we can switch to using a released version
Signed-off-by: James Rawlings <jrawlings@chainguard.dev>
=> add an action that can be used from another GitHub Action

.github/workflows/golangci-lint.yaml, .gitignore, .golangci.yaml, cmd/docs/main.go, cmd/docs/man_docs.go, cmd/docs/md_docs.go, pkg/cli/lint.go, pkg/cli/update.go, pkg/cli/vex.go, pkg/gh/github.go, pkg/lint/linter.go, pkg/lint/types.go, pkg/update/githubReleases.go, pkg/update/githubReleases_test.go, pkg/update/mapper.go, pkg/update/releaseMonitor.go, pkg/update/update.go, pkg/update/update_test.go, pkg/vex/vex.go, pkg/vex/vex_test.go
This PR adds golangci-lint into the repository and fixes all errors in the code. It fixes some minor bugs and starts to remove deprecated code from some modules. It also adds a new job to run golangci-lint in a presubmit.
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>
=> Add golangci-lint job, fix errors and bugs

pkg/lint/rules.go, pkg/lint/rules_test.go, pkg/lint/testdata/files/bad-template-var.yaml
Signed-off-by: Dan Lorenc <dlorenc@chainguard.dev>
=> Add a new lint rule for bad template vars, likely copied from APKBUILDs.

pkg/cli/vex.go
(and a handful of small spelling fixes)
=> Rename packages cmd to package

pkg/advisory/advisory.go, pkg/advisory/sync/need.go, pkg/cli/advisory.go, pkg/cli/advisory_create.go, pkg/cli/advisory_list.go, pkg/cli/advisory_sync_secfixes.go, pkg/cli/advisory_update.go, pkg/configs/index.go
This adds a new `--sync` flag to `wolfictl advisory create` and `... update`. When used, this will automatically update the config's `secfixes:` section to stay in sync with the modifications made to the `advisories:` section, if needed.
Once the advisories section is stable, we'll stop using secfixes altogether. But we're not quite there yet, and we want to make sure we're still building accurate secdbs in the meantime.
=> Add --sync flag to advisory create and update

pkg/vex/testdata/git.yaml, pkg/vex/vex_test.go
There were two issues with the test `vex.TestFromPackageConfiguration` (that were my fault :picard-facepalm:):
1. The test was passing when it shouldn't have been, because errors from parsing Melange configs were ignored.
2. This hid another issue where the test would've failed because the VEX doc generation was generating timestamps non-deterministically.
The latter issue has been addressed in https://github.com/chainguard-dev/vex/pull/52. In #13, we'll import that update into this repo, which should mean we can safely compare timestamps in this test.
=> Fix vex test issues

pkg/cli/bump.go, pkg/cli/commands.go
From the help text:
```
wolfictl bump increases the epoch field in melange configuration files
The bump subcommand allows increments version numbers in packages. For now it will only bump epoch numbers but a future version will allow users to control versions expressed in semver.
wolfictl bump can take a filename, a package or a file glob, increasing the version in each matching configuration file
```
This works by doing a string replacement on the epoch field in the yaml configs. It does no re-marshaling at all as it was causing a huge diff.
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>
=> Add wolfictl bump subcommand

pkg/cli/bump.go
Previously the `wolfictl bump` command did not update the makefile when bumping the epoch.
=> bump: update makefile when bumping

pkg/cli/apk.go, pkg/cli/commands.go
Commands to pull remote apks and APKINDEX and print information about them to stdout as JSON, so you can `jq` it.
```
$ go run . apk busybox-1.36.0-r0.apk | jq -r .RepoCommit
8d3ed829b595b36d679fe91a1843685f0256c2b8
```
```
$ go run . index | jq -r '.Packages[].Name' | head -n 10
bash-doc
pkgconf-doc
wolfi-baselayout
glibc-locale-nso
lz4-dev
automake-doc
glibc-locale-rw
libxi-dev
libev-dev
glibc-locale-syr
```
If other output formats are useful we can add them. If a more interactive apk picker is useful we can add that too. If we want to support other package repos, we can. The world is our oyster 🦪 
Signed-off-by: Jason Hall <jason@chainguard.dev>
=> Add apk and index subcommands

pkg/cli/apk.go
```
$ wolfictl apk cross-linux-headers-5.16.9-r0 --repo=stage1
{
"Name": "cross-linux-headers",
"Version": "5.16.9-r0",
"Arch": "x86_64",
"Description": "the Linux kernel headers (cross compilation)",
...
```
```
$ wolfictl index --repo=stage1
{
"Signature": "...",
"Description": "",
"Packages": [
{
"Name": "cross-linux-headers",
...
```
In addition to the handful of known repos we care about, the `--repo` flag accepts a URL prefix, in case you have any other APK repos you want to query:
```
$ wolfictl index --repo=https://dl-cdn.alpinelinux.org/alpine/edge/main
{
"Signature": "...",
"Description": "v3.17.0-5638-g1149277d63",
"Packages": [
{
"Name": "bacula-libs",
```
Signed-off-by: Jason Hall <jason@chainguard.dev>
=> apk,index: support repo flag, append .apk if absent

pkg/update/package.go, pkg/update/package_test.go
Signed-off-by: James Rawlings <jrawlings@chainguard.dev>
=> wolfictl update, fix regex to handle CVE names with hyphen separators

pkg/cli/lint.go, pkg/lint/linter.go, pkg/lint/options.go, pkg/melange/melange.go
This also contains a fix to not be so strict when checking if a yaml file is indeed a melange config.  We are seeing linting being applied to files that are not melange configs, this assumes a bare minimum that package name and package version are set, to indicate a yaml file should be linted.
=> wolfictl lint: allow users to skip rules via a CLI flag

pkg/cli/update.go, pkg/cli/update_package.go, pkg/git/git.go, pkg/update/package.go, pkg/update/update.go
- add option to enable gitsign to sign the commits
this will enable us to sign the commits using gitsign
related to https://github.com/wolfi-dev/tools/pull/7
tested locally 
```shell
$ /Users/cpanato/code/src/github.com/wolfi-dev/wolfictl/wolfictl update package grafana --version v0.0.4 --target-repo https://github.com/cpanato/enterprise-packages --use-gitsign
Enumerating objects: 50, done.
Counting objects: 100% (50/50), done.
Compressing objects: 100% (44/44), done.
Total 50 (delta 14), reused 29 (delta 3), pack-reused 0
2023/02/15 15:31:39 wolfictl update: no fixes: CVE### comments found from commits between tags v0.0.3 and v0.0.4, skip creating sec fix advisories
2023/02/15 15:31:39 attempting to bump version to 0.0.4
Your browser will now be opened to: …
```
=> add option to enable gitsign to sign the commits

pkg/lint/rules.go, pkg/lint/rules_test.go, pkg/lint/testdata/files/bad-version.yaml
This is copied from apko: https://github.com/chainguard-dev/apko/blob/v0.7.0/pkg/apk/impl/version.go#L25-L27, which is itself copied from apk's `version.c`.
=> add lint check for valid versions

pkg/lint/linter.go, pkg/lint/rules_test.go, pkg/lint/testdata/files/nolint.yaml, pkg/melange/melange.go
Related to #81 I'd like to be able to require a lint check across the repo, but also allow some files to opt out of specific rules.
If a file contains a line that starts with `#nolint:` (no spaces), any lint rules that follow, comma-separated, are ignored (see added test file). Only the first `#nolint:` line is considered.
=> support #nolint: to disable rules per-file

pkg/cli/commands.go, pkg/cli/make.go, pkg/dag/graph.go
Request for feedback, with some remaining TODOs to fix graph generation to handle `provides:`es.
Anyway, the idea is that `wolfictl make` will generate a DAG of targets and build them in order, invoking `make packages/aarch64/helm-3.11.1-r1.apk`, etc.
This wouldn't let us get rid of the Makefile completely, but it _would_ let us drop the hand-curated list of targets which must be kept in order.
=> add `wolfictl make` to execute `make` for us

pkg/advisory/advisory.go
This is a super minor change — but it makes it a bit easier to tell when a run of `wolfictl advisory discover` has come up with net new vulnerabilities to address, since the only log entries are now for actionable vulns.
=> Don't log existing advisories during discovery

pkg/cli/pod.go
Following on from https://github.com/wolfi-dev/os/pull/866 and https://github.com/wolfi-dev/os/pull/901, this makes the ~same change in our Arm builds.
=> pod: don't cache APKINDEX when copying to GCS

pkg/lint/linter.go, pkg/lint/testdata/dir/Makefile
With wolfi-dev/os now changed to use packages in a separate file, rather than in the Makefile, `wolfictl lint` reads the wrong thing and fails.
This PR updates it to call `make list`, using that as an API to report all known packages, and finds them that way.
=> lint calls make list and checks package names

pkg/update/githubReleases.go
- avoids overwriting an error message if no results found
- add "pre" to the list of version suffixes we can't compare and therefore auto update
=> wolfi update: a couple of improvements noticed after updating a lot more packages

go.mod, go.sum, pkg/cli/lint.go, pkg/cli/lint_yam.go, pkg/configs/yaml.go
The new command is: `wolfictl lint yam`. You can optionally pass one or more file/dir to lint; if no args are provided, the current directory is linted.
This introduces a dependency on the `diff` command, which is used to show the diff between a file's expected state and its actual state.
This also updates the YAML encoder to use the latest version of Yam.
cc: @rawlingsj
=> Add new command for checking that config YAML files are formatted correctly

pkg/checks/so_name.go, pkg/checks/so_name_test.go, pkg/checks/testdata/packages.log, pkg/checks/testdata/subpackages_melange.yaml
I changed Melange's `packages.log` to emit origin + subpackage fields, e.g.
```
aarch64|openssl|openssl-provider-legacy|3.1.0-r4
```
This chases that format update.
=> checks: so-name: support subpackages-inclusive packages.log format

go.mod, go.sum, pkg/dag/graph_test.go, pkg/dag/testdata/busybox.yaml
This is causing the "Dependency analysis" CI check to fail in Wolfi.
=> Fix panic caused by dag Graph and new logger interaction

pkg/checks/so_name.go
`TempDir` returns "/tmp" on UNIX machines, and is not an equivalent to `mktemp(3)`.
`MkdirTemp` returns "/tmp/[pattern]", and is equivalent to `mktemp(3)`.
=> checks: so-name: use MkdirTemp instead of TempDir to get a temporary directory

pkg/checks/update.go, pkg/checks/update_test.go, pkg/update/githubReleases.go, pkg/update/update.go
Now that wolfi has package update config for all packages, let's keep it that way so wolfi is easier to maintain.  It will mean that this is the last time we will need to spend a large amount of time adding update configs to a lot of packages.
=> wolfi check update: ensure update config is provided

go.mod, go.sum, pkg/configs/index.go, pkg/configs/index_test.go, pkg/configs/testdata/index-1/.not-a-config.yaml, pkg/configs/testdata/index-1/config-1.yaml, pkg/configs/testdata/index-1/subdir/not-a-config.yaml
(needs to bring in changes from https://github.com/chainguard-dev/melange/pull/395 before it's ready)
This fixes an issue where a configs index was being built to include YAML files from subdirectories when it shouldn't.
This also adds tests around the `NewIndex` function to make sure the right YAML files are getting included or not included.
=> Fix directory descension for configs index

pkg/checks/update.go
@rawlingsj would love your opinion here. The old check was just seeing if the versions weren't equal, but it tripped over an edge case [here](https://github.com/wolfi-dev/os/actions/runs/4758448256/jobs/8456519341?pr=1501#step:5:489). The [melange file](https://github.com/wolfi-dev/os/blob/main/ruby3.2-yajl-ruby.yaml#L56) in question has to use the commit rather than the version because the yajl author released a gem with security fixes but did not cut a tag on GitHub.
The `update` section marks the config to be manually updated, but the version comparison in the update checks only checks if the versions aren't equal which throws an error even if the detected version on GitHub is less than melange. I could see strictly checking if the versions are equal as a good behavior for a linter …
=> Update Checks - switch Equal to LessThan

pkg/lint/rules.go, pkg/lint/rules_test.go, pkg/lint/testdata/files/no-epoch.yaml
The melange struct for epoch doesn't have an `omitempty` yaml annotation which means it is always 0 when unmarshalling configs.  This lint check validates the raw yaml to make sure epoch is set.
This will help avoid these issues https://github.com/wolfi-dev/os/issues/1569
=> wolfictl lint: ensure packages have an epoch set

pkg/cli/pod.go
We had some builds fail with an error indicating the gcloud-cp container OOMed. We don't set a request, but we should.
=> set resource request for gcloud-cp step

pkg/advisory/db.go, pkg/advisory/db_test.go, pkg/advisory/testdata/db/advisories/brotli.advisories.yaml, pkg/advisory/testdata/db/advisories/ko.advisories.yaml, pkg/advisory/testdata/db/advisories/openssl.advisories.yaml, pkg/advisory/testdata/db/security.json, pkg/cli/advisory.go, pkg/cli/advisory_db.go
This implements the `wolfi-secdb generate` command from https://github.com/wolfi-dev/secdb as the new command `wolfictl advisory db`.
To ensure parity, this logic was implemented against a test fixture secdb (`security.json`) that was generated by `wolfi-secdb`.
cc: @kaniini
=> Add a command to generate a security database ("secdb")

pkg/cli/advisory.go, pkg/cli/advisory_create.go, pkg/cli/advisory_db.go, pkg/cli/advisory_discover.go, pkg/cli/advisory_list.go, pkg/cli/advisory_sync_secfixes.go, pkg/cli/advisory_update.go, pkg/distro/detect.go, pkg/distro/detect_test.go
Now that there are multiple distros managed using `wolfictl`, and now that there are two repos per distro (one for the distro itself, with package configs, and one for advisory data), things are getting slightly more complicated. 😰 
Advisory-related commands need to know about the advisories repo (for reading and writing data), and some of these commands also need to know about the distro repo that corresponds to that advisories repo (for reading data). Since multiple local directories are involved, it's not always possible to assume a given operation is intended for the current working directory, because that directory can't be both _the distro repo_ and _the advisories repo_ at the same time.
As of a recent update, users can tell `wolfictl` explicitly where their local clones of the …
=> advisory commands: add distro auto-detection, and add flags to disable this detection and interactive prompts

pkg/advisory/db.go, pkg/advisory/db_test.go, pkg/advisory/testdata/db/other-advisories/cups.advisories.yaml, pkg/advisory/testdata/db/security-multiple.json, pkg/cli/advisory_db.go
=> Guard against using dirs with no security data, and add support for multiple advisory repo dirs

pkg/advisory/discover.go, pkg/cli/advisory.go, pkg/cli/advisory_discover.go, pkg/distro/detect.go, pkg/distro/detect_test.go
This updates the `wolfictl adv discover` command by letting the package repository URL (used as the prefix to the APKINDEX) to be determined dynamically via distro detection. This reduces the need for users to use the `--package-repo-url` during discovery.
Going forward, as more commands become "APKINDEX-aware", this pattern can carry forward to similarly auto-resolve the URL on users' behalf.
=> Set apkindex URL prefix based on detected distro

pkg/cli/pod.go
A follow-up to https://github.com/wolfi-dev/wolfictl/pull/210
=> apkindex publishing: preserve ACL rather than set it

pkg/cli/advisory.go, pkg/cli/advisory_create.go, pkg/cli/advisory_update.go, pkg/cli/components/advisory/field/field.go, pkg/cli/components/advisory/field/list_field.go, pkg/cli/components/advisory/field/text_field.go, pkg/cli/components/advisory/prompt/model.go, pkg/cli/styles/styles.go, pkg/distro/detect.go, pkg/distro/distro.go, pkg/versions/versions.go, pkg/versions/versions_test.go
This PR builds on the distro auto-detection added in #208 and the interactive TUI (terminal UI) added in #204 by adding validation and automatic suggestions to the TUI based on user input.
This improves the experience of running the `wolfictl adv create` and `wolfictl adv update` commands:
1. The `Package:` field uses package names found in the distro repo (for `create`) or advisories repo (for `update`).
2. The `Vulnerability:` field validates that the input is a valid CVE ID, and for `update` ensures that the CVE ID corresponds to an existing advisory.
3. The `Fixed Version:` field uses package versions from the APKINDEX and the current build configuration, providing a default value of the current package version.
The theory is that these UX improvements will make it even more appealing …
=> advisory: autosuggest and validation

Makefile
We still had the broken install lines for pipelines, and it did not depend on the actual build. Fixes both.
=> remove broken makefile lines and fix deps

pkg/cli/pod.go
I realized this as I want to revert my other change that we would hit the "dubious permission" issue and need this command to accept the workspace as a safe directory.  🤞 
See also: https://github.com/chainguard-dev/kontext/blob/347f191bd8d465631acc627f8a8309e01016fce0/.github/workflows/e2e-test.yaml#LL64C21-L64C72
=> Mark the workspace as a safe directory for git operations.

scripts/setup-cluster.sh
The fix applied in https://github.com/chainguard-images/images/pull/557 to include `mount` only made that change to `:1.3.3`, so pinning to `:1.3.2` didn't pick it up.
Ideally we should just be on `:latest` but that can be a separate PR.
Annoyingly, the missing-`mount` failure only happens when the secret is actually used, and doesn't manifest just in seeing the DaemonSet come up.
=> fix secrets-store-csi-driver by using latest version

go.mod, go.sum, pkg/dag/graph.go
With the v0.22.0 release of the underlying graph, we can sort it not only by ensuring antecedents come before their descendants (which it already did), but also have a consistent sorting algorithm for equal-level nodes. In our case, we do a simple lexicographical sort.
=> use stable sorting for graph

scripts/setup-cluster.sh
As we see in #224, pinning to a specific version means we have to remember to update the version to pick up any fixes.
This PR has us depend on `:latest` for secrets-store-csi-driver{-provider-gcp}.
If we're worried about this being disruptive, we can put a digestabot in place so that upgrades are discrete and acknowledged, but automated.
=> use :latest secrets-store-csi images

go.mod, go.sum, pkg/dag/graph.go, pkg/dag/packages.go
This only gets it down to about 245s for the graph, so another 10-15s, but it helps. I believe the last bump will have to come from inside the graph algorithm.
=> cache repos in graph; use go-apk

pkg/advisory/validate.go, pkg/cli/advisory.go, pkg/cli/advisory_validate.go
This adds in a rudimentary approach to validating advisory data, intended to be used locally and in CI to give folks confidence about proposed updates to advisory data.
There are no tests included, because as soon as I'm back from vacation, these data models are going to change. When those updates are made, we'll keep the validation functionality and update it with proper tests.
Example output:
```console
$ wolfictl advisory validate
Auto-detected distro: Wolfi
issue(s) found with advisories file for package "busybox": 
issue(s) found with advisory "CVE-2022-28391": 
issue(s) found with event 1 (of 1): 
status is "component_not_present" but must be one of [not_affected, affected, fixed, under_investigation]
fixed version must be empty if status is not "fixed" …
```
=> Add `advisory validate` command

pkg/update/update.go
release monitor jobs have been failing since a packge update contained a bad URL which means the bort worklflow creates an issue rather than a PR.
Lables were added a couple of weeks ago to help with project board management.
This will fix the error we are seeing:
```
Error: creating updates: POST https://api.github.com/repos/wolfi-dev/os/issues: 422 Invalid request.
For 'properties/labels', nil is not an array. []
time="2023-06-06T16:59:35Z" level=fatal msg="error during command execution: creating updates: POST https://api.github.com/repos/wolfi-dev/os/issues: 422 Invalid request.\n\nFor 'properties/labels', nil is not an array. []"
```
https://github.com/wolfi-dev/os/actions/runs/5191079332/jobs/9358423759
=> fix release monitor bot on wolfi

pkg/dag/packages.go
We open this file for seemingly no reason.
=> Remove useless file open/close

pkg/cli/pod.go
In case the apkindex is somehow made private, this will force it back to public.
This isn't supported by the gcloud surface, so switch to gsutil, which doesn't have `--cache-control`, so switch to `-h "Cache-Control"` instead
=> always make apkindex public

pkg/cli/pod.go
Undoes https://github.com/wolfi-dev/wolfictl/commit/77f5b2900be23bb0172137e549c9f2cef3da6d00 which seems to cause errors uploading APKINDEX for arm64 builds
```
2023-06-13T00:24:35.2542771Z CommandException: Incorrect option(s) specified. Usage:
2023-06-13T00:24:35.2543058Z 
2023-06-13T00:24:35.2543221Z   gsutil cp [OPTION]... src_url dst_url
2023-06-13T00:24:35.2543610Z   gsutil cp [OPTION]... src_url... dst_url
2023-06-13T00:24:35.2544255Z   gsutil cp [OPTION]... -I dst_url
2023-06-13T00:24:35.2544437Z 
2023-06-13T00:24:35.2544569Z For additional help run:
2023-06-13T00:24:35.2544859Z   gsutil help cp
```
Also improve logging.
=> revert gsutil change

pkg/dag/graph.go, pkg/dag/testdata/complex/one-dupl.yaml, pkg/dag/testdata/complex/one.yaml, pkg/dag/testdata/complex/three.yaml, pkg/dag/testdata/complex/two.yaml
The DAG calculation before did not account for runtime dependencies, i.e. those listed in `package.dependencies.runtime` as correctly pointed out by @kaniini. This updates it to account for those. The `.runtime` dependencies are to be resolved solely from the local package list, i.e. no upstream.
In order to make this work, we had to rearrange the package additions to the graph. It makes it easier to understand anyways, which is a good thing. It now is:
1. Do a loop through all packages, adding each package as a graph node, adding each subpackage as a graph node, dependent on the parent
2. Do a loop through all packages, adding each runtime dependency; this only works after the previous step, as all packages and subpackages need to exist as nodes before we can add the runtime dependencies …
=> Add runtime deps to graph

pkg/cli/pod.go
this replicates the change made to x86 builds on wolfi, details and further explanation found in this PR from @imjasonh  https://github.com/wolfi-dev/os/pull/2969
=> pod: don't upload apks if they already exist

pkg/cli/commands.go, pkg/cli/ls.go, pkg/ls/ls.go, pkg/ls/ls_test.go, pkg/ls/testdata/buildconfigs/acl.yaml, pkg/ls/testdata/buildconfigs/aom.yaml, pkg/ls/testdata/buildconfigs/apko.yaml
Adds new root command `wolfictl ls`. This command lists packages that are defined in the given directory.
(This command uses "advisory-command-style" auto-detection or specified via `-d <path/to/distro/directory>`.)
```console
$ wolfictl ls
7zip
acl
acme.sh
aerospike
alpine-keys
alsa-lib
...
```
Specify `-s`/`--subpackages` to include subpackages.
```console
$ wolfictl ls -s
7zip
7zip-doc
acl
acl-dev
libacl1
```
Pass package names as args to select a specific package. This is operating on _parsed_ configurations, **so factors like `range` data are already considered.**
```console
$ wolfictl ls -s glibc
glibc
ld-linux
glibc-dev
...
glibc-locale-af
glibc-locale-agr
glibc-locale-ak
glibc-locale-am
glibc-locale-an
glibc-locale-anp
glibc-locale-ar
glibc-locale-as
glibc-locale-ast …
```
=> Add ls command for listing and querying package configs

pkg/cli/dot.go, pkg/cli/make.go, pkg/cli/pod.go, pkg/cli/text.go, pkg/dag/graph_test.go, pkg/dag/packages.go, pkg/dag/packages_test.go
This enables us to define custom pipeline directories to use outside of the ones built-in to melange.
https://github.com/wolfi-dev/os/pull/3579 added such a pipeline for Wolfi, `go-fips/build`, which was `go/build` but using `go-fips` instead of `go`. It probably doesn't make sense to have this defined in Melange itself.
With this change, `wolfictl text` considers the `--pipeline-dir` passed to it when determining the build graph, instead of failing to find the pipeline.
=> support --pipeline-dir anywhere we can

pkg/cli/update.go, pkg/update/githubReleases.go, pkg/update/testdata/query_tags/result, pkg/update/update.go
- use smaller batches when querying githubs API
- add retry logic to help when we have a bad git state, i.e. causing issues like this https://github.com/wolfi-dev/os/issues/3587
=> wolfi updates: a few improvements as we are seeing the occasional failure

pkg/distro/distro.go
Otherwise, if a user has remotes like what's below ⬇️ , the `wolfictl advisory ...` commands won't be able to find the distro and advisory repos.
```text
upstream    https://github.com/wolfi-dev/advisories (fetch)
upstream    https://github.com/wolfi-dev/advisories (push)
```
=> Distro detect: allow git remotes without .git suffix

pkg/cli/pod.go
This is an attempt to get our private packages' APKINDEXes to stop getting reset to private when we update them.
- https://cloud.google.com/sdk/gcloud/reference/storage/cp#--canned-acl
- https://cloud.google.com/storage/docs/access-control/lists#predefined-acl
This was attempted before in https://github.com/wolfi-dev/wolfictl/pull/259/files (reverted in https://github.com/wolfi-dev/wolfictl/pull/264) using `gsutil cp -a`. I'm not sure why we didn't use `gcloud storage cp --canned-acl` at that time, it may not have been supported then, but is now:
> This isn't supported by the gcloud surface[...]
=> Use --canned-acl=publicRead

pkg/cli/commands.go, pkg/cli/sbom.go, pkg/sbom/sbom.go
Similar to the `wolfictl scan` command, this command lets you target a local APK file and inspect it for packages, using Syft. The default view is a summary outline. But you can also get an SBOM in Syft format using `-o syft-json`. The motivation for supporting this output format is to feed it into a soon-to-come revision of the `scan` command.
Preview:
And w/ `-o syft-json`:
=> Add new 'sbom' command

pkg/cli/components/advisory/field/text_field.go, pkg/cli/components/advisory/prompt/model.go
Two improvements:
- Remove character limit for text fields (it had been `32`)
- Prompt for `impact` field when status is `not_affected`
=> Minor advisory prompt improvements

pkg/cli/pod.go
Reverts wolfi-dev/wolfictl#305
```
2023-07-21T18:53:35.1371014Z Copying file://./packages/aarch64/APKINDEX.tar.gz to gs://wolfi-production-registry-destination/os/aarch64/APKINDEX.tar.gz
2023-07-21T18:53:35.1481180Z   
2023-07-21T18:53:35.6403211Z ERROR: HTTPError 400: Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access
```
=> Revert "Use --canned-acl=publicRead"

pkg/sbom/pkginfo.go, pkg/sbom/sbom.go
This updates `wolfictl sbom` to include an APK-type package in the SBOM as well, where the data is drawn from the APK's embedded `.PKGINFO` file.
Preview:
=> sbom: synthesize APK package and add to SBOM

.github/workflows/build.yaml
This should hopefully help us guard against DAG regressions that affect wolfi-dev/os's usage before we find out about them when we start using them in that repo.
=> ci: check that `wolfictl text` runs on wolfi-dev/os

.github/workflows/release.yaml, README.md
In my repo: 
- https://github.com/imjasonh/wolfictl/actions/workflows/release.yaml
- https://github.com/imjasonh/wolfictl/tags
In my tests I couldn't manually run this until it had run one time automatically, so if we want to test this out before Monday we'll need to add another trigger and remove it after it works.
=> cut weekly patch releases

pkg/advisory/advisory.go, pkg/cli/sbom.go, pkg/cli/scan.go, pkg/sbom/sbom.go, pkg/scan/apk.go, pkg/scan/filter.go, pkg/scan/filter_test.go, pkg/scan/testdata/advisories/ko.advisories.yaml
This adds a new feature to `wolfictl scan` that uses advisory data to filter out scan results that are already accounted for in the advisory data. This will help anyone working on adding new advisory data based on scan data by reducing the "noise" of what's already been covered in the advisory data.
There are two ways to use the advisory data to do filtering:
1. Filter out "resolved" advisories, which will leave only scan results where we're still affected, or we're not sure yet whether we're affected
2. Filter out "all" advisories, which will hide **_any_** scan results where there is any kind of advisory recorded for that vulnerability
To use this feature, you need to provide:
- `--advisory-filter`/`-f`: the set of advisories to use in filtering (set this to `resolved` or `all`)
- …
=> scan: filter out results using advisory data

go.mod, go.sum, pkg/configs/index.go
Previously, the use of `.AutomaticConfig()` was reading the yam config from the current working directory, even if `wolfictl` was interacting with advisory data in a _different_ directory, and the net result was that the correct formatting wasn't used for the advisories directory.
cc: @ajayk @kaniini
=> fix: use correct yam config for non-cwd advisories

README.md, pkg/cli/sbom.go, pkg/cli/scan.go, pkg/sbom/cache.go, pkg/sbom/sbom.go
A few useful improvements to the SBOM generation capability that's used in both `wolfictl sbom` and `wolfictl scan`:
1. JSON output is now **deterministic**.
2. SBOM data is now **cached** by default, so subsequent `sbom` and `scan` commands on a given APK file are _NOTICEABLY_ faster. This cache can be disabled with `--disable-sbom-cache`.
3. The distro ID value can now be set explicitly with `--distro` (it defaults to "wolfi").
---
Also, adds installation instructions to the README. 😁
=> SBOM-related optimizations

go.mod, go.sum, pkg/sbom/sbom.go
To produce an SBOM for an APK package, in addition to running Syft on the APK's data section, `wolfictl` also synthesizes a package entry for the APK itself using its control section.
This PR adds CPE and PURL data to that synthesized APK package in the SBOM.
Example:
```jsonc
{
// ...
"cpes": [
"cpe:2.3:a:skaffold:skaffold:2.6.2-r0:*:*:*:*:*:*:*"
],
"purl": "pkg:apk/wolfi/skaffold@2.6.2-r0?arch=aarch64&origin=skaffold",
// ...
}
```
=> feat(sbom): generate PURL and CPEs for APK package

go.mod, go.sum
These make it needlessly difficult to `go install`
The alpine-go replace was so we could fetch apks slightly faster using `wolfictl apk` (which nearly nobody uses), and the other one is equivalent to just `require`ing that version.
=> remove replace directives

pkg/cli/apk.go, pkg/cli/commands.go, pkg/cli/pod.go
This PR:
- Removes a no longer used `wolfictl generate-index` command
- Adjusts the `wolfictl pod` command to set the APKINDEX object's ACL to `publicRead` on copy when uniform bucket level access is disabled, which we hope ensures that the APKINDEX is always public
cc: @jonjohnsonjr @imjasonh
=> APKINDEX fixes

pkg/advisory/export.go, pkg/advisory/export_test.go, pkg/cli/advisory_export.go
This change adds the option to export all advisories in a single YAML output:
```
wolfictl adv export --format yaml
```
I haven't added a test for this yet. The output order of the map of events isn't predictable yet, and it causes some instability. The format for advisories V2 will allow to test this a lot easier!
=> Add option to export in YAML

pkg/cli/scan.go
```sh
$ curl -s https://packages.wolfi.dev/os/aarch64/crossplane-provider-aws-0.39.0-r0.apk | go run ./ scan -
Will process apk from stdin
$ go run ./ scan https://packages.wolfi.dev/os/aarch64/crossplane-provider-aws-0.39.0-r0.apk            
Will process: https://packages.wolfi.dev/os/aarch64/crossplane-provider-aws-0.39.0-r0.apk
```
=> scan: support https URLs and stdin

pkg/cli/build.go, pkg/cli/dot.go, pkg/cli/pod.go, pkg/cli/text.go
This is a dependency of https://github.com/wolfi-dev/os/pull/5257 but is probably a good idea regardless.
This adds `--keyring-append` and `--repository-append` to commands in `wolfictl` that deal with the dep graph. This makes it possible to switch on/off bootstrap-awareness as compatible with https://github.com/wolfi-dev/os/pull/5257 for dep graph construction.
=> add -k and -r to graph-using commands

pkg/cli/components/advisory/field/field.go, pkg/cli/components/advisory/field/list_field.go, pkg/cli/components/advisory/field/text_field.go, pkg/cli/components/advisory/prompt/model.go, pkg/configs/advisory/v2/advisory.go
- should prompt for "note" value for new event types: fix-not-planned, analysis-not-planned
- prompt should allow empty "note" response for true positives, since the field is optional
- prompt should require a non-empty "note" response for false positives
- non-empty response values were followed by the prompt askig for the same field again
- change event index from 0-based to 1-based in advisory validation messages
=> fix: minor issues with advisory prompts

pkg/cli/text.go
This was previously a flag in `wolfictl text`, but I think it should just always be true.
If this lands well I will remove the option to set it to false and always have it be true.
=> always use buildtime repos for runtime resolution

pkg/advisory/discover.go, pkg/cli/advisory_discover.go, pkg/cli/components/advisory/field/text_field.go, pkg/cli/components/advisory/matchwatcher/model.go, pkg/cli/styles/styles.go, pkg/vuln/detector.go, pkg/vuln/event.go, pkg/vuln/match.go, pkg/vuln/nvdapi/detector.go
This is just a superficial and refactoring change to the `wolfictl adv discover` command. This PR creates a new TUI component for showing the per-package vulnerability searches. This also starts to incorporate some of the UI elements from `wolfictl scan`.
=> feat: better UI for advisory discovery

pkg/scan/apk.go, pkg/scan/filter.go, pkg/scan/filter_test.go
This was something I overlooked in the initial implementation of the filtering flags (i.e. `-f`/`-a`) for `wolfictl scan`.
Now, when scanning a subpackage APK, and applying advisory data to filter out scan results, the command will look up the origin package for the APK, and use that to find advisory entries. (Advisory data is always filed under the origin package name, never for the subpackage directly.)
cc: @vaikas
=> fix: find advisories for origin package during scan filtering

pkg/advisory/alias_finder.go, pkg/advisory/discover_aliases.go, pkg/advisory/discover_aliases_test.go, pkg/advisory/export.go, pkg/advisory/testdata/discover_aliases/advisories/.yam.yaml, pkg/advisory/testdata/discover_aliases/advisories/scenario-1.advisories.yaml, pkg/advisory/testdata/discover_aliases/advisories/scenario-2.advisories.yaml, pkg/advisory/testdata/discover_aliases/advisories/scenario-3.advisories.yaml, pkg/advisory/testdata/discover_aliases/advisories/scenario-4.advisories.yaml, pkg/advisory/testdata/discover_aliases/advisories/scenario-5.advisories.yaml, pkg/advisory/testdata/discover_aliases/advisories/scenario-6.advisories.yaml, pkg/advisory/testdata/discover_aliases/advisories/scenario-7.advisories.yaml, pkg/advisory/update.go, pkg/cli/advisory.go, pkg/cli/advisory_alias.go, pkg/cli/advisory_alias_discover.go, pkg/cli/advisory_alias_find.go, pkg/cli/advisory_create.go, pkg/cli/advisory_discover.go, pkg/cli/advisory_list.go, pkg/cli/advisory_update.go, pkg/cli/advisory_validate.go, pkg/configs/advisory/v2/advisory.go, pkg/configs/advisory/v2/advisory_test.go, pkg/configs/advisory/v2/event.go, pkg/configs/advisory/v2/migrate.go, pkg/configs/selection.go
This PR adds two new commands:
- `wolfictl adv alias discover`: looks up aliases in supported vulnerability data sources (for now, just GHSA) to populate the `aliases` field on existing advisories.
- `wolfictl adv alias find`: a simple utility command that looks up aliases for the vulnerability IDs provided as arguments on the command line. (This command doesn't touch any advisory data.)
This PR makes it easier to ensure we stay aware of relevant vulnerability records in the upstream data sources we care about.
This is already a large PR, but future PRs could look at the following enhancements to take this PR's functionality further...
1. Automatically discover aliases as part of the `wolfictl adv create` command.
2. Automatically discover aliases as part of the `wolfictl adv discover` …
=> feat: add rich support for advisory aliases

pkg/dag/graph.go
`--keyring-append` and `--keyring-append` weren't being piped through here, leading to graph breakages when repos/keys were passed this way vs. in the YAML.
=> fix: use extra repos in graph calculation

pkg/configs/advisory/v2/fixed.go, pkg/configs/advisory/v2/fixed_test.go, pkg/lint/rules.go, pkg/versions/validate.go, pkg/versions/validate_test.go
Previously, `wolfictl adv validate`, when validating `v2.Fixed` data, would only check that the fixed version field was not empty. The expectation should have been that these versions are valid for Wolfi, and that they include an epoch suffix (in fact, some of our current data is invalid in this regard and needs to be fixed!).
This PR makes the fixed version more robust, by leveraging an existing version check used in Melange file linting. That check has been moved to the `versions` package and exported for broader use.
cc: @imjasonh
=> Better version validation

pkg/buildlog/buildlog.go, pkg/buildlog/buildlog_test.go, pkg/buildlog/testdata/packages.log, pkg/cli/sbom.go, pkg/cli/scan.go
In some workflows, when we build packages, we ask Melange to create a "build log" of the packages that it outputs. (This can be accomplished with the `melange build` flag called `--create-build-log`.)
This PR adds an enhancement to the `wolfictl scan` command to determine the set of APKs to scan off the build log, so we can scan _N_ packages that we just built.
For example, I just did a Melange build of the "jansson" package, which also has 1 subpackage:
```console
$ cat packages.log 
aarch64|jansson|jansson|2.14-r0
aarch64|jansson|jansson-dev|2.14-r0
$ wolfictl scan --build-log .                                        
🔎 Scanning "packages/aarch64/jansson-2.14-r0.apk"
🔎 Scanning "packages/aarch64/jansson-dev-2.14-r0.apk"
```
The new …
=> feat(scan): ability to base scan(s) on a Melange build log

pkg/buildlog/buildlog.go, pkg/cli/scan.go, pkg/scan/filter.go, pkg/scan/filter_test.go, pkg/scan/testdata/advisories-additional/.yam.yaml, pkg/scan/testdata/advisories-additional/ko.advisories.yaml
This PR makes the following improvements to `wolfictl scan`:
- When using `--build-log`, APK package paths are now resolved relative to the provided build log path, rather than to the current working directory (since build logs and `packages/<arch>/*.apk` files are virtually always colocated)
- When using `--require-zero` to exit 1 on a failed scan, we now allow all scans to complete before exiting, rather than exiting on the first failed scan in a group
- You can now use the `-a` flag multiple times to leverage advisory data from multiple local directories at the same time (when filtering scan results)
=> wolfictl scan: various improvements

go.mod, go.sum, pkg/cli/advisory_alias_discover.go, pkg/cli/gh_gc_branch.go, pkg/cli/update.go, pkg/cli/update_package.go
This change makes it so you don't need a `GITHUB_TOKEN` env var set if you've previously set up and authorized [GitHub's `gh` CLI](https://cli.github.com/) -- if you have, the token used by that CLI will be used.
[`TokenForHost`](https://pkg.go.dev/github.com/cli/go-gh/v2/pkg/auth#TokenForHost) checks `GITHUB_TOKEN` and falls back to a plaintext file or secure keyring storage.
=> look for GH tokens used by gh CLI

pkg/advisory/create.go, pkg/advisory/discover_aliases.go, pkg/advisory/discover_aliases_test.go, pkg/advisory/export.go, pkg/advisory/update.go, pkg/cli/advisory.go, pkg/cli/advisory_list.go, pkg/cli/components/advisory/prompt/model.go, pkg/configs/advisory/SCHEMA_VERSIONS.md, pkg/configs/advisory/v2/advisory.go, pkg/configs/advisory/v2/analysis_not_planned.go, pkg/configs/advisory/v2/document.go, pkg/configs/advisory/v2/document_test.go, pkg/configs/advisory/v2/event.go, pkg/configs/advisory/v2/fix_not_planned.go, pkg/configs/advisory/v2/pending_upstream_fix.go, pkg/configs/advisory/v2/section_updaters.go, pkg/configs/advisory/v2/testdata/full.advisories.yaml, pkg/scan/testdata/advisories/ko.advisories.yaml
This revs the advisory schema to version `2.0.1`, which adds a non-breaking change:
- A new event type `PendingUpstreamFix`
This addresses an emergent need where the distro staff either isn't able to implement the fix on the upstream maintainers' behalf in a reasonable amount of time, or where doing so introduces more risk to the security of the software than leaving the fix to the upstream maintainers to take on.
This is a distinct state from `FixNotPlanned`, which says that a fix is never coming.
It's also distinct from `TruePositiveDetermination`, which acknowledges the vulnerability's impact on the package but doesn't communicate the distro staff's plan for remediation.
=> Advisory schema v2.0.1: new PendingUpstreamFix event type

pkg/cli/update.go, pkg/update/update.go
Optional flag to instruct wolfictl to look for melange yaml files in a sub-dir of the git repo.
Rebased PR https://github.com/wolfi-dev/wolfictl/pull/401 to avoid force pushing changes on a non wolfi repo.  Commit is still associated with the initial contribution from @joemiller
=> feat(pkg subdir): add `--path` flag to `wolfictl update`

.github/workflows/golangci-lint.yaml, cmd/docs/main.go, cmd/docs/md_docs.go, pkg/checks/diff_test.go, pkg/checks/update.go, pkg/cli/advisory.go
We were seeing different results in CI vs. the local experience — including a case where applying a local "fix" _breaks_ the results in CI — which makes it painful to run the check locally. Ideally running the local check rewards developers by shifting "left" feedback that would come back in CI to the local iteration workflow.
This PR updates CI to use the latest version of `golangci-lint` and fixes the new linting issues that get reported.
=> Fix linter parity with local development

pkg/cli/scan.go
A frequent pain in today's scanning is having to get a hold of a particular APK file _before you can scan it_. This means you either have to wait to _build it_ first (with melange), or you need to _find the APK_ in the APKINDEX (or in the backend infrastructure), and you need to figure out which version+epoch is the latest one.
When investigating a report of a vulnerability in package, the person doing the investigation often doesn't have the APK already at the time they're beginning their task.
This PR adds a new `--remote`/`-r` flag to `wolfictl scan`, that tells the command to interpret the arg(s) as package names (e.g. "crane") instead of as paths to APK files.
When this flag is used, `wolfictl` will dynamically figure out the latest published version of the package with the specified …
=> feat(scan): ability to scan Wolfi packages remotely by name

pkg/cli/commands.go, pkg/cli/withdraw.go
This just operates on the APKINDEX.tar.gz and a list of packages (with their versions) to withdraw. It uses stdin and stdout for the old and new index and takes a --signing-key flag.
=> Add wolfictl withdraw command

pkg/cli/withdraw.go
Current withdrawn-packages.txt list assumes .apk.
=> Support .apk suffix in wolfictl withdraw

pkg/scan/apk.go
Grype misses some Java matches (including some true positives) that other scanners seem to catch.
This change enables [this feature in Grype](https://github.com/anchore/grype#external-sources), which gives Grype better metadata for Maven packages such that it can more reliable find relevant matches when it searches its database for GHSA matches.
cc: @pdeslaur @found-it @rawlingsj @jedsalazar
=> fix(scan): reduce Java FNs via Maven search

go.mod, go.sum, pkg/checks/update.go, pkg/dag/packages.go, pkg/update/githubReleases.go, pkg/update/githubReleases_test.go
This PR introduces two new filters  **`tag-filter-prefix`** and **`tag-filter-contains`**, to the GitHub Release filtering . These features enhance the filtering capabilities when preparing versions.
`tag-filter-prefix` option ensures that only tags that start with the specified prefix are considered. the functionality is same as the `tag-filter`
`tag-filter-contains` option ensures that only tags containing the specified substring are considered.
**``deprecation-notice``** : we would like to deprecate `tag-filter` in favor of `tag-filter-prefix`  , once all the configurations are moved over , we will remove supporting `tag-filter`
=> feature: add tag-filter-prefix and tag-filter-contains

pkg/checks/diff.go
- use a code block to avoid markdown trying to parse `-`s as bullets
- mention that `.PKGINFO` is metadata, not file contents
=> improve .PKGINFO diff

pkg/cli/scan.go, pkg/scan/apk.go
For the `wolfictl scan` command, this adds a `--use-cpes` flag that restores the across-the-board CPE matching behavior that Grype used to have, resulting in (sometimes a ton) more matches to NVD records in scan results.
cc: @pdeslaur
=> feat(scan): add flag to re-enable CPE matching

pkg/advisory/diff_test.go, pkg/advisory/testdata/diff/added-event/b/ko.advisories.yaml, pkg/advisory/testdata/diff/modified-advisory-outside-of-events/a/ko.advisories.yaml, pkg/advisory/testdata/diff/modified-advisory-outside-of-events/b/ko.advisories.yaml, pkg/advisory/validate.go, pkg/advisory/validate_test.go, pkg/cli/advisory.go, pkg/cli/advisory_alias_discover.go, pkg/cli/advisory_create.go, pkg/cli/advisory_diff.go, pkg/cli/advisory_discover.go, pkg/cli/advisory_export.go, pkg/cli/advisory_list.go, pkg/cli/advisory_secdb.go, pkg/cli/advisory_update.go, pkg/cli/advisory_validate.go, pkg/cli/ls.go, pkg/configs/advisory/v2/advisory.go, pkg/configs/advisory/v2/detection.go, pkg/configs/advisory/v2/document.go, pkg/distro/detect.go, pkg/distro/detect_test.go, pkg/distro/distro.go, pkg/git/git.go, pkg/internal/errorhelpers/labeled_error.go
This PR enhances the `wolfictl adv validate` command by validating the "diff" of advisory data relative to a known base state. This PR takes advantage of and extends the advisory diffing functionality introduced in #478.
=> feat(adv): validate diff in data from base state 

pkg/distro/detect.go, pkg/distro/detect_test.go
This fixes a case where resolving the git ref on the upstream repo wasn't working correctly, where the resulting ref hash was all zeros, and thus the fork point wasn't guaranteed to exist on the upstream commit history.
=> fix: distro detect: better upstream ref resolution

pkg/advisory/diff_test.go, pkg/advisory/testdata/diff/added-advisory/b/ko.advisories.yaml, pkg/advisory/testdata/diff/added-document/b/ko.advisories.yaml, pkg/advisory/testdata/diff/added-event-with-non-recent-timestamp/a/ko.advisories.yaml, pkg/advisory/testdata/diff/added-event-with-non-recent-timestamp/b/ko.advisories.yaml, pkg/advisory/validate.go, pkg/advisory/validate_test.go, pkg/cli/advisory_validate.go
This adds a component to advisory diff validation, where events that were just added must have a timestamp that's "recent".
"Recent" is currently defined as being no more than 3 days old, but that's up for discussion if anyone has an argument for adjusting this to be more loose or more strict.
Here's an example of what a validation failure looks like using this new feature:
```console
$ w adv validate
Auto-detected distro: Wolfi
invalid change(s) in diff:
syft:
CVE-3333-33333:
event 1 (just added):
event's timestamp (2023-11-11T23:40:17Z) set to more than 3 days ago; timestamps should accurately capture event creation time
```
=> feat(adv): validate timestamp on new events

pkg/advisory/diff_test.go, pkg/advisory/testdata/validate/alias-missing-cve/ko.advisories.yaml, pkg/advisory/testdata/validate/alias-missing-ghsa/ko.advisories.yaml, pkg/advisory/testdata/validate/alias-not-missing/ko.advisories.yaml, pkg/advisory/validate.go, pkg/advisory/validate_test.go, pkg/cli/advisory_alias_discover.go, pkg/cli/advisory_validate.go
This adds a check in `wolfictl adv validate` to make sure that all discoverable aliases have been found and added correctly.
Here's a sample of what failing this check looks like:
```
Auto-detected distro: Wolfi
alias set completeness validation failure(s):
minio:
GHSA-2wrh-6pvc-2jm9:
"GHSA-2wrh-6pvc-2jm9" should be listed as an alias, and "CVE-2023-3978" should be the advisory ID
CVE-2023-44487:
missing GHSA alias "GHSA-qppj-fm5r-hxr3" from set [GHSA-m425-mq94-257g, GHSA-2222-2222-2222]
```
**Note:** One potential issue is that frequent runs of `wolfictl adv validate` now risk hitting a user's rate limit with the GitHub API. @rawlingsj has a suggestion of switching the underlying querying to use GraphQL instead of the Rest API, to batch calls in groups of a …
=> feat(adv): validate completeness of alias sets

pkg/advisory/testdata/validate/package-existence/advisories/ko.advisories.yaml, pkg/advisory/testdata/validate/package-existence/advisories/mo.advisories.yaml, pkg/advisory/testdata/validate/package-existence/distro/ko.yaml, pkg/advisory/validate.go, pkg/advisory/validate_test.go, pkg/cli/advisory_validate.go
This adds a new check to `wolfictl adv validate` to make sure that the package named in a given advisory document is currently defined in a build configuration in the corresponding distro packages repository (using the local clone of said repository).
Here's an example of failure output for this check:
```
Auto-detected distro: Wolfi
package existence validation failure(s):
argo-cd:
this package is not defined in any distro package configuration
```
**Also:** This PR adds new flags that can turn off specific aspects of validation:
```
--skip-alias                         skip alias completeness validation
--skip-diff                          skip diff-based validations
--skip-existence                     skip package configuration existence validation
```
=> feat(adv): validate package definition existence

pkg/lint/rules.go, pkg/lint/rules_test.go, pkg/lint/testdata/files/idn-homograph-attack.yaml
This detects if a fetch URL uses IDN lookalike domains such as `xⅰph.org` instead of 
`xiph.org`.
For more context, see https://en.wikipedia.org/wiki/IDN_homograph_attack
=> lint: detect IDN homograph attacks

pkg/advisory/validate.go, pkg/advisory/validate_test.go, pkg/cli/advisory.go, pkg/cli/advisory_create.go, pkg/cli/advisory_update.go, pkg/cli/advisory_validate.go
This updates the validation check implemented in #494. Rather than require all advisory documents to describe packages currently defined in the distro, the rules are now as follows:
- Net new advisory documents must refer to packages currently defined in the distro
- Modified advisory documents must refer to packages either currently defined in the distro, or that exist in the distro's APKINDEX (such as because they were _formerly_ defined in the distro)
- There are no package existence requirements for advisory documents being removed
=> fix: base existence check on diff conditions

pkg/sbom/sbom.go
There were recent breaking changes in Syft where numerous cataloger names were updated.
This PR resyncs the list of configured catalogers to Syft's catalogers using their latest explicit names, by:
- Starting with all [image catalogers](https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/cataloger.go#L42-L64) (for the sake of parity w/ Syft/Grype image scanning)
- Removing irrelevent catalogers (e.g. debian)
- Removing the SBOM cataloger and other catalogers that shouldn't be in Syft's image cataloger list (like cpp/Conan) — will follow up with them on these cataloger choices
=> fix(sbom,scan): resync configured catalogers

pkg/configs/advisory/v2/detection.go, pkg/configs/advisory/v2/document_test.go, pkg/configs/advisory/v2/event.go, pkg/configs/advisory/v2/testdata/future.advisories.yaml
In various parts of the advisory schema, during decoding, we had been requiring that enum values are known to wolfictl, so that we knew which data structure to use to parse the corresponding `Data  interface{}` field.
This causes a problem where non-breaking future schema changes trigger breakages in the current version of wolfictl during decoding.
This PR adds a test (which fails before making the rest of the changes in this PR) to assert that future enum values don't result in an error on decoding.
Thanks to @pdeslaur for finding this!
cc: @rawlingsj
=> fix(adv): error decoding future enum values

pkg/advisory/diff_test.go, pkg/configs/advisory/SCHEMA_VERSIONS.md, pkg/configs/advisory/v2/detection.go, pkg/configs/advisory/v2/detection_test.go, pkg/configs/advisory/v2/document.go, pkg/configs/advisory/v2/document_test.go, pkg/configs/advisory/v2/testdata/full.advisories.yaml
This PR adds a new non-breaking ("addition") advisory schema update: **v2.0.2**.
This adds support for capturing valuable information from a vulnerability scan into an advisory's **detection** event(s).
This also tests out the idea of "versioned" types in the advisory schema, here by introducing a new detection type of `scan/v1`. This is intended to allow us to iterate on the data shape such that multiple versions of this detection type can coexist in a single advisory data set, and newer detections can always take advantage of the latest data structure available.
The hope is that by adding this library support, we can begin automatically generating advisory data using vulnerability scans, such that we're not losing the insightful data found at scan-time as we encode the detection into …
=> feat(adv): v2.0.2 schema

.github/workflows/build.yaml, pkg/dag/packages.go, testdata/text/org/bar/bar.melange.yaml, testdata/text/org/foo/foo.melange.yaml, testdata/text/root.yaml
This starts to support cases where the repo containing Melange configs isn't just a flat directory.
It does support the current flat structure:
```
foo.yaml
bar.yaml
baz.yaml
```
...as well as a nested structure like:
```
blah/foo/foo.melange.yaml
blah/bar/bar.melange.yaml
hello/baz/baz.melange.yaml
```
(NB: files must be named like `*.melange.yaml`, otherwise they're ignored -- the directory name is not currently taken into account, but could be)
...and an intermediate stage where the repo may have some files in the flat structure and some in the nested structure:
```
foo.yaml
blah/bar/bar.melange.yaml
baz.yaml
```
The `foo.yaml` does not currently need to describe a package with `name: foo` -- we might add this later. A `foo.melange.yaml` doesn't need to be contained in a directory …
=> wolfictl text: support nested repo structure

go.mod, go.sum, pkg/dag/packages.go
Need to plumb through the latest melange changes because without it things are failing in wolfi-dev/os because it doesn't know about new fields.
https://github.com/wolfi-dev/os/pull/9982
like this:
https://github.com/wolfi-dev/os/actions/runs/7225997373/job/19690633526?pr=9982
=> Bring in the latest melange to handle `test` configurations.

pkg/cli/text.go, pkg/dag/graph.go, pkg/dag/graph_options.go
The `wolfictl text` command is ignoring `--arch` argument, always running for x86 arch.
```bash
❯ ./../wolfictl/wolfictl text
2023/12/28 01:05:21 Skipping non-melange YAML file: kubeflow-pipelines/metadata-envoy-config.yaml
2023/12/28 01:05:22 Skipping non-melange YAML file: loki/local-config.yaml
2023/12/28 01:05:22 Skipping non-melange YAML file: loki/promtail-local-config.yaml
2023/12/28 01:05:22 Skipping non-melange YAML file: pipelines/bitnami/compat.yaml
2023/12/28 01:05:22 Skipping non-melange YAML file: pipelines/go/bump.yaml
2023/12/28 01:05:22 Skipping non-melange YAML file: pipelines/ruby/unlock-spec.yaml
2023/12/28 01:05:22 [DEBUG] GET https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz
2023/12/28 01:05:23 [DEBUG] GET …
```
=> feat: fix --flag arg in text command

go.mod, go.sum, pkg/git/submodules/update.go
The use of both v5 and v4 seems unintentional. Dropping v4 prunes our deps a little bit.
=> Use go-git v5 everywhere

pkg/advisory/validate.go, pkg/advisory/validate_test.go, pkg/cli/advisory.go, pkg/cli/advisory_validate.go
Adds (structured) logging to the advisory code, starting here with the validation functionality.
This logging is off by default, but CLI users can turn on info-level logs with `-v`, and debug-level logs with `-vv`.
Library users can customize the `*slog.Logger` they provide to the `advisory.ValidateOptions` struct however they like.
Example:
```console
$ w adv validate --skip-alias -vv
time=2024-01-09T11:19:39.253-05:00 level=DEBUG msg="distro auto-detection enabled"
time=2024-01-09T11:19:40.418-05:00 level=INFO msg="detected distro" name=Wolfi
time=2024-01-09T11:19:40.418-05:00 level=DEBUG msg="local distro properties" packagesRepoDir=/Users/dan/code/wolfi-os advisoriesRepoDir=/Users/dan/code/wolfi-advisories advisoriesRepoForkPoint=6635d8bf071aef86c5665c14ea803e7c9a939a47 …
```
=> feat(adv): add logging to validation

go.mod, go.sum, pkg/cli/advisory.go, pkg/configs/build/build.go, pkg/internal/nop_slogger.go
To avoid a default logger being used via https://github.com/chainguard-dev/clog, this introduces a no-op logger that does nothing, that can be injected into contexts explicitly to prevent downstream calls from having side effects.
This also updates an existing "no-op" use case in advisory validation with a better one.
This also updates Melange to incorporate this fix: https://github.com/chainguard-dev/melange/pull/936
cc: @imjasonh @jonjohnsonjr
=> fix: explicitly do not log

pkg/sbom/sbom.go
Don't catalog APK packages from SBOMs in the APKs, just use `.PKGINFO`.
(Soon we'll add integration tests to ensure we're getting consistent results from Syft and Grype.)
=> fix(sbom,scan): exclude SBOM cataloging

.github/workflows/release.yaml
Some releases are redundant, since no changes happen during the intervening time. We should try to avoid these.
This is an attempt to avoid these.
=> release: don't bump tags if no changes

go.mod, pkg/checks/update.go, pkg/update/deps/cleanup.go, pkg/update/deps/cleanup_test.go, pkg/update/deps/testdata/config-1.yaml, pkg/update/deps/testdata/config-1_expected.yaml, pkg/update/deps/testdata/config-2.yaml, pkg/update/deps/testdata/config-2_expected.yaml, pkg/update/deps/testdata/config-3.yaml, pkg/update/deps/testdata/config-3_expected.yaml, pkg/update/deps/testdata/config-4.yaml, pkg/update/deps/testdata/config-4_expected.yaml, pkg/update/deps/testdata/config-5.yaml, pkg/update/deps/testdata/config-5_expected.yaml, pkg/update/deps/testdata/config-6.yaml, pkg/update/deps/testdata/config-6_expected.yaml, pkg/update/update.go
I’ve coded over the weekend an extension to our `wolfictl update package` command to cleanup go/bump dependencies or even to remove that pipeline if it is not needed anymore. 
This feature reuses the changes to update a package (new tag, repo, ...) and pulls the repository/tag looking for a go.mod file. Once it finds the go.mod file, it verifies whether the go/bump deps can be removed from the list based on the existing deps included in this new version of the package. 
**This feature will help us to keep our Wolfi definitions clean without manual intervention.**
NOTE: this feat only supports package updates where we use `git-checkout` pipelines.
I share here a [PR](https://github.com/hectorj2f/os/pull/31/files) where the `go/bump` dep is removed because the upstream new version of the …
=> feat: cleanup gobump deps/replaces or even remove the pipeline if not needed

docs/cmd/wolfictl_scan.md, docs/man/man1/wolfictl-scan.1, pkg/cli/scan.go, pkg/configs/advisory/v2/advisory.go, pkg/scan/filter.go, pkg/scan/filter_test.go
As part of a discussion in https://chainguard-dev.slack.com/archives/C0636FTRFED/p1705946151427929, we decided to add a new filter type so we can filter the advisory data to remediate certain CVE types such as true-positive, pending-upstream-fix and not-fixed...
=> chore: add a new advisory filter set

pkg/lint/linter.go, pkg/lint/rules.go, pkg/lint/rules_test.go, pkg/lint/testdata/files/bad-version-nolint-forbid.yaml, pkg/lint/testdata/files/nolint.yaml, pkg/lint/types.go
This PR adds ability to forbid some `nolint:` directives for the rules. For example, we should not allow `nolint:bad-version` since it results in `package file format error` while attempting to install with `apk add`.
=> rules: add check to forbid nolint directive for bad-version

pkg/sbom/sbom.go
Syft and Grype don't seem to be handling OpenJDK properly, such that **we miss valid vulnerability matches** (i.e. false negatives) in our `openjdk-*` APKs when using Syft and Grype in `wolfictl` to scan the APK.
This PR implements a potentially viable workaround that lets us discover these vulnerabilities after all.
```console
$ wolfictl scan --disable-sbom-cache =(curl -sS https://packages.wolfi.dev/os/aarch64/openjdk-21-21.0.1-r0.apk)
🔎 Scanning "/tmp/zshp5wsUm"
```
```console
$ wolfictl scan --disable-sbom-cache =(curl -sS https://packages.wolfi.dev/os/aarch64/openjdk-21-21.0.1-r0.apk)
🔎 Scanning "/tmp/zshryD2h3"
└── 📄 /.PKGINFO
📦 openjdk-21 21.0.1-r0 (apk)
High CVE-2024-20918
Medium CVE-2024-20926
High CVE-2024-20952
```
=> fix(scan): CPE matching for OpenJDK packages

pkg/lint/rules.go
Reverts wolfi-dev/wolfictl#581
=> Revert "make invalid SPDX identifier an error"

pkg/checks/update.go, pkg/update/deps/cleanup.go, pkg/update/deps/cleanup_test.go, pkg/update/update.go
We disable the submodule recursion because we are just interested on the current module when looking for `go.mod` files. If this doesn't improve the performance, we could even attempt fetch the `go.mod` file itself although this could get more complicated when we don't know the location of the go.mod file.
=> cleanup: improve perf when cloning git repos

pkg/checks/update.go, pkg/update/deps/cleanup.go, pkg/update/deps/cleanup_test.go, pkg/update/deps/testdata/config-9.yaml, pkg/update/deps/testdata/config-9_expected.yaml, pkg/update/update.go
We now check in advance before cloning any repo if the package definition contains a go-bump pipeline to attempt cleaning unused deps.
=> cleanup: skip if go/bump pipeline was not found

pkg/cli/advisory_validate.go
Today the alias validation makes many calls to the GitHub API. This works for some people, if they're authenticated, but can also result in rate limiting from the API, particularly if no subset of packages is selected on the command line (i.e. with `-p`).
In the future, an implementation is possible that avoids these API calls altogether by querying a local cache of GitHub's data.
But for now, to avoid toil, we'll default this check to off. It can be re-enabled by using `--skip-alias=false`.
cc: @mamccorm
=> fix(adv): skip alias validation by default

pkg/advisory/diff.go, pkg/advisory/testdata/validate/duplicate-advisory-by-id-and-alias/ko.advisories.yaml, pkg/advisory/testdata/validate/duplicate-advisory-by-id/ko.advisories.yaml, pkg/advisory/testdata/validate/no-duplicates/ko.advisories.yaml, pkg/advisory/validate_test.go, pkg/configs/advisory/v2/document.go
This will catch when both IDs and aliases are reused when they shouldn't be.
Example output:
```console
basic validation failure(s):
kube-state-metrics-2.6:
advisories:
CVE-2023-3978: advisory ID is not unique
GHSA-2wrh-6pvc-2jm9: advisory alias is not unique
metrics-server-fips:
advisories:
GHSA-45x7-px36-x8w8: advisory ID is not unique
```
=> Advisory validation: start detecting duplicate IDs being used

main.go
This propagates context cancellation instead of immediately quitting.
=> Use signal.NotifyContext in main

pkg/sbom/sbom.go
before we have this in the source section
```
"source": {
"id": "(redacted for determinism)",
"name": "os/x86_64/argo-cd-2.8-2.8.7-r5.apk",
"version": "",
"type": "directory",
"metadata": {
"path": "os/x86_64/argo-cd-2.8-2.8.7-r5.apk"
}
},
```
after the change we will have
```
"source": {
"id": "(redacted for determinism)",
"name": "conftest",
"version": "0.47.0-r2",
"type": "directory",
"metadata": {
"path": "/Users/cpanato/Downloads/conftest-0.47.0-r2.apk"
}
},
```
this will help in the cve automation to check the version of an apk sbom
=> update source data for apk sbom to include apk name and version instead of the path

pkg/update/deps/cleanup.go
Fixes the wolfi bot update job which is currently failing https://github.com/wolfi-dev/os/actions/runs/8108959477/job/22163187753
```
2024/03/01 09:16:05 INFO checking the pipeline: { go/bump map[deps:golang.org/x/net@v0.17.0]  [] map[] {[]}   {0}  map[]}
panic: runtime error: slice bounds out of range [:-1]
goroutine 1 [running]:
github.com/wolfi-dev/wolfictl/pkg/update/deps.cleanupGoBumpPipelineDeps(0xc002b809b8, {0xc00f3c0a20, 0x18}, 0x0)
github.com/wolfi-dev/wolfictl/pkg/update/deps/cleanup.go:143 +0x1c7e
```
=> wolfictl update: fix panic when dropping bumps

go.mod, pkg/advisory/import.go, pkg/advisory/import_test.go
This will help the lifecycle to import an yaml document and avoid us to clone the repo
=> add import yaml function

pkg/advisory/import.go, pkg/advisory/import_test.go
follow up https://github.com/wolfi-dev/wolfictl/pull/665
=> receive a byte not the path for a file

pkg/cli/build.go
This lets us see at a glance what order packages were built in.
=> build: Add span with package name

pkg/apk/apk.go, pkg/apk/apk_test.go, pkg/apk/testdata/APKINDEX.json
This add a function to parse an apkIndex in json format
This will be use read the apkindex from gcs instead going to the LoadBalancer
=> Add ParsePackageIndexFromJSON

pkg/update/deps/cleanup.go
While checking go/bump pipelines via the function `CleanupGoBumpDeps`
We were not placing the git repository into the desired destination it caused failure when the repo is cloned into a destination repository. with error `error cleaning up go/bump deps: unable to parse the go mod file with error: open /tmp/wolfibump379243584/<specified-destination>/go.mod: no such file or directory`
Example:
- https://github.com/wolfi-dev/os/actions/runs/8200210238/job/22426545029?pr=14379
- https://github.com/wolfi-dev/os/actions/runs/8201144492/job/22429289256?pr=14382
=> FIx Bug: git-checkout into proper destination

pkg/configs/advisory/v2/advisory.go, pkg/scan/filter.go, pkg/scan/filter_test.go
Over the last 3-4 weeks, we found several instances where some package update PRs have removed valuable CVE fixes from a package. The latest example is `datadog-agent`, here's a rough sequence of events:
1. A new CVE is found: CVE-2024-23653
2. A language-level dependency update fixes the CVE: https://github.com/wolfi-dev/os/pull/12350
3. A new "fixed" advisory is filed in our dataset, noting the APK version that fixes the CVE: https://github.com/wolfi-dev/advisories/pull/1140
<< Issue begin >>
4. A new version of the package is available, the package is updated, but we incorrectly remove the CVE fix: https://github.com/wolfi-dev/os/pull/13291
At this point, the vulnerability scan comes back clean since we have already filed a `fixed` advisory and we have a blindspot. In practice, the …
=> advisory: Don't filter fixed advisories affecting non-apk from scan results

pkg/cli/scan.go
Before:
```
wolfictl scan test
❌ Skipping scan because SBOM generation failed for "test": failed to open input file: failed to open input file: open test: no such file or directory
🔎 Scanning "test"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103bad734]
goroutine 52 [running]:
github.com/wolfi-dev/wolfictl/pkg/scan.newTargetAPK(0x0)
/Users/jonjohnson/src/github.com/wolfi-dev/wolfictl/pkg/scan/apk.go:72 +0x54
github.com/wolfi-dev/wolfictl/pkg/scan.(*Scanner).APKSBOM(0x14000658c30, 0x0)
/Users/jonjohnson/src/github.com/wolfi-dev/wolfictl/pkg/scan/apk.go:162 +0x30
github.com/wolfi-dev/wolfictl/pkg/cli.(*scanParams).doScanCommandForSingleInput(0x14000358150, {0x104ec1690, 0x14000b5acc0}, 0x11?, 0x0, …
```
=> scan: Actually skip on err instead of pretending

pkg/cli/build.go
The logic I had for intersecting the target-architectures and --arch
flags introduced a race condition where single-arch packages would
overwrite the global archs configuration, which led to bad things.
=> Un-revert un-group by arch, fix race

pkg/checks/diff.go
This was only showing up on diffs, which is unfortunate. We also want to see .PKGINFO for new packages.
=> diff: Print .PKGINFO for new packages

pkg/cli/build.go
This ended up in the log file instead of stderr because of how I wired up the log file context.
=> build: Restore log line for starting pkg build

pkg/cli/build.go, pkg/cli/text.go, pkg/dag/graph.go, pkg/dag/graph_test.go, pkg/dag/packages.go, pkg/dag/testdata/subpackages/one.yaml, pkg/dag/testdata/subpackages/three.yaml, pkg/dag/testdata/subpackages/two.yaml
Previously, we would just filter out any non-main packages in our build graph. Unfortunately, that filtered out any edges to subpackages that were important for build ordering.
As one real example, consider this dependency:
spdlog -> fmt-dev
Since spdlog depends on fmt-dev, we need to build fmt-dev before we can build spdlog.
We can't build fmt-dev directly, since it's a subpackage of fmt, so we need to build fmt before we build spdlog.
Before this change, that edge would just get dropped and we would try to build spdlog and fmt at the same time. The spdlog build would fail because fmt-dev would not exist until after fmt completes.
With this change, dag.Graph.Targets() essentially flattens any subpackage nodes in the graph so that they are equivalent to the main package.
So after calling …
=> build: Consider subpackages for build order

pkg/cli/build.go
Since we were just returning the error, it wouldn't show up in the build log, which was very confusing. Now it will show up both in stderr and the build log.
=> build: Include build error line in log file

pkg/cli/commands.go, pkg/cli/test.go, pkg/dag/packages.go
adds `wolfictl test`.
attempts to reuse things that make sense from `wolfictl build`, but since we don't really care about executing the tests in the appropriate dag order, the amount of re-use is pretty minimal.
this uses a simpler `errgroup` to dispatch (in alphabetical order).
this also supports testing a single, multiple, or all packages depending on the positional args provided.
sample use case for this: https://github.com/wolfi-dev/os/pull/16351
=> add wolfictl test command

docs/advisory_guide_flow.md, go.mod, go.sum, pkg/advisory/alias_finder.go, pkg/advisory/data_session.go, pkg/advisory/request.go, pkg/cli/advisory_diff.go, pkg/cli/advisory_guide.go, pkg/cli/components/breather/breather.go, pkg/cli/components/ctrlcwrapper/ctrlcwrapper.go, pkg/cli/components/interview/interview.go, pkg/cli/components/picker/picker.go, pkg/cli/internal/builds/builds.go, pkg/cli/internal/questions/questions.go, pkg/cli/internal/utils.go, pkg/cli/scan.go, pkg/cli/styles/styles.go, pkg/distro/detect.go, pkg/distro/detect_test.go, pkg/distro/detectv2.go, pkg/distro/distro.go, pkg/vuln/url.go
This PR is a (substantial) follow-up to https://github.com/wolfi-dev/wolfictl/pull/631, which introduced a partially implemented `wolfictl adv guide` command.
To recap, the purpose of this command is to rethink the user experience of entering advisory data for a package.
This PR introduces several notable improvements to the original state:
1. **Short-lived advisory data sessions** — This command is the first to try a new approach, where `wolfictl` no longer expects you to have cloned any advisories repos in advance. Instead, when you run the command, it grabs the latest data from GitHub, makes updates to that data on your behalf locally, and then lets you open a PR with your changes — all without having had to interact with YAML. This is driven by a new internal `advisory.DataSession` …
=> advisory guide: enabling advisory data entry by interview

pkg/advisory/question/questions.go, pkg/cli/advisory_guide.go, pkg/cli/components/interview/interview.go, pkg/cli/components/picker/picker.go, pkg/cli/components/textinput/textinput.go, pkg/question/graph/dot.go, pkg/question/graph/dot_test.go, pkg/question/question.go
This PR iterates on the `wolfictl adv guide` command:
1. Adds support for **free text input** when needed, in addition to just multiple choice answers.
2. Expands the interview with more questions and answers. Updated interview graph shown below.
=> feat(adv): support free text input and iterate on guide interview flow

pkg/advisory/question/questions.go, pkg/cli/advisory_guide.go, pkg/cli/components/accept/accept.go, pkg/cli/components/interview/interview.go, pkg/cli/internal/wrapped/wrapped.go, pkg/question/graph/dot.go, pkg/question/graph/dot_test.go, pkg/question/question.go
Enhances the interview process by:
- Allowing the interview to include "messages", which are like questions but only user choice is to accept the message and move on. Animation included below.
- Allowing interview answers to result in terminating the interview early, such that the tracked state is **_not_** persisted (e.g. with advisory data, this discards the state rather than writing to the local advisory data session). Logically this is handled by a question's answer function returning `question.ErrTerminate`.
- Finishing a "complete" first draft of the advisory guide interview process, where all TODOs have been replaced with real behavior. The latest interview graph is shown below.
=> feat(adv): messages to the user within the interview

pkg/advisory/import.go
if we import two different advisories dataset the last one override the first and then it fail
seeing an error in the scan apk packages
```
failed to import advisory data wolfi-production-registry-destination/os/advisories.yaml: unable to index advisory configs for directory "/tmp": unable to open configuration at "hey.advisories.yaml": open /tmp/hey.advisories.yaml: no such file or directory
```
=> create a random temp file when importing the adv data

pkg/checks/diff.go
This is to lower the amount of bincapz change noise we see.
Alternatively, we should set a default flag value for GitHub actions, but then we run into the messy issue of "wolfictl check" behaving different than our GHA checks.
=> check: increase bincapz file threshold from 1 to 3

pkg/scan/apk.go
After my Grype PR (https://github.com/anchore/grype/pull/1797), Anchore added a follow-up PR that makes this behavior cnofigurable. It is on by default for the Grype CLI but not for the Grype library. This commit enables it for the Grype library so we can see this kind of match from wolfictl scans.
E.g.:
```console
$ wolfictl scan ./packages/aarch64/atlantis-0.27.2-r2.apk
🔎 Scanning "./packages/aarch64/atlantis-0.27.2-r2.apk"
└── 📄 /usr/bin/atlantis
📦 github.com/runatlantis/atlantis v0.0.0-20240308212341-29919209f2a1 (go-module)
High CVE-2022-24912 GHSA-jxqv-jcvh-7gr4 fixed in 0.19.7
📦 golang.org/x/net v0.19.0 (go-module)
Medium CVE-2023-45288 GHSA-4v7x-pqxf-cx7m fixed in 0.23.0
```
=> fix(scan): enable pseudoversion comparison

pkg/cli/advisory_validate.go, pkg/cli/advisory_validate_fixes.go
This prototypes a new command that can take a directory of APK files, along with a directory of advisory data, and verify that any vulnerabilities found in the APK files in a fresh scan are not listed as "fixed" in the advisory data.
Example:
```console
$ wolfictl adv validate fixes -a ./wolfi-advisories -b ./wolfi-os/packages/aarch64
❌  atlantis: 0.27.2-r2 does not fix CVE-2023-45288: found golang.org/x/net @ v0.19.0 in /usr/bin/atlantis
2024/04/24 08:10:27 INFO error during command execution: invalid fixed advisories found
```
=> feat(adv): command to validate advisory fix data

pkg/versions/versions.go, pkg/versions/versions_test.go
This is related to the issue reported on slack [here](https://chainguard-dev.slack.com/archives/C05GYUBM07Q/p1713943656535999) where a list of versions as such `[0.1.0-r12, 0.1.0-r9, 0.1.0-r1]` always returned `0.1.0-r9` as the latest.
=> fix: compare package version epoch as numerics

pkg/cli/advisory_guide.go, pkg/cli/sbom.go, pkg/cli/scan.go, pkg/sbom/cache.go, pkg/sbom/sbom.go, pkg/scan/apk.go, pkg/scan/filter.go, pkg/scan/filter_test.go
- ⚠️ **BREAKING**: The the API of several library methods associated with SBOM generation and vulnerability scanning have been modified in a breaking way.
- ⚠️ **BREAKING**: Scan result filtering with advisories now takes at most one advisories dir/index; multiple were never needed, so this simplifies the operation.
- 📜 Logging with clog and contexts has been plumbed extensively into SBOM generation and vulnerability scanning.
- 🔨  Fix: When the scan command fetched a remote APK, this temp file is now cleaned up after scanning, whereas it was not before.
cc: @cpanato @hectorj2f @rawlingsj @jonjohnsonjr
=> fix(sbom,scan)!: BREAKING CHANGES, see description

go.mod, go.sum, pkg/scan/apk.go
This is a follow-up to #792 that removes the need to regress the Syft/Grype versions used while still avoiding a known source of false positives in the meantime.
cc: @rawlingsj
=> scan: turn off Go main module version matching for now

go.mod, go.sum
Upgrade melange to pick up https://github.com/chainguard-dev/melange/pull/1142 which adds back
the golang symbols table to all binaries.
=> go bump melange for golang symbols

go.mod, go.sum
Only 2 changes being pulled in here.
1. Only consider commands in a PATH dir from generateCmdProviders https://github.com/chainguard-dev/melange/pull/1164
2. Allow symlinks to provide cmd: https://github.com/chainguard-dev/melange/pull/1188
=> Update melange dependency for 2 'provides' changes.

pkg/cli/build.go
This existence check didn't seen to work and got our CI wedged, so log the error in case that happens again in the future.
=> build: Log error from apk stat

pkg/lint/rules.go, pkg/lint/testdata/files/missing-github-update-git-checkout.yaml
Only require github-update when git checkouts actually are from
github.com rather than from freedesktop gitlab debian salsa etc.
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@chainguard.dev>
=> lint: github.com is not the only git hosting

pkg/git/git.go, pkg/git/git_test.go
This fixes a panic, and adds some security paranoia while we are at it.
`go run . update http://stromberg.org/`
```
panic: runtime error: index out of range [2] with length 2
goroutine 1 [running]:
github.com/wolfi-dev/wolfictl/pkg/git.ParseGitURL({0x16b40b86d, 0x15})
/Users/t/src/wolfictl/pkg/git/git.go:119 +0x58c
github.com/wolfi-dev/wolfictl/pkg/git.GetGitAuth({0x16b40b86d, 0x15})
/Users/t/src/wolfictl/pkg/git/git.go:28 +0x8c
```
`go run . update https://apache.googlesource.com/abdera`
```
panic: runtime error: index out of range [2] with length 2
goroutine 1 [running]:
github.com/wolfi-dev/wolfictl/pkg/git.ParseGitURL({0x16bac385c, 0x26})
/Users/t/src/wolfictl/pkg/git/git.go:119 +0x58c
github.com/wolfi-dev/wolfictl/pkg/git.GetGitAuth({0x16bac385c, 0x26}) …
```
=> git: fix panic while handling non-github git URLs, disallow plain-text http

pkg/internal/bundle/bundle.go
Apparently --binary-data buffers everything into memory.
=> bundle: Switch to --upload-file for curling data

go.mod, go.sum
This resolve `wolfictl lint` reporting 4 packages of wolfi-dev/os as
having invalid licenses, when they are, in fact, valid.
Fixes: #841
=> Update go-spdx with more licenses

pkg/lint/rules.go
valid-copyright-header already enforces non-empty license.
Quite a few files use "PROPRIETARY" (i.e. Nvidia) or "custom" for
non-spdx standardtised licences. Everything else must be valid from
now on.
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@chainguard.dev>
=> lint: require custom, proprietary or valid SPDX license tag

pkg/internal/bundle/bundle.go
Use an emptyDir as build usage of /tmp is variable and if /tmp is /tmpfs may fill up
=> Use emptyDir for builder /tmp

pkg/internal/bundle/bundle.go
bundle build: set node affinity for podspec to use n2,n2d,t2a, this allows request of 32+ core builds
=> bundle build: set node affinity for podspec to use n2,n2d,t2a, this allows request of 32+ core builds

pkg/internal/bundle/bundle.go
missed this the first time around: 
`Warning: Node auto-provisioning doesn't support multiple value assigned to the node affinity. Make sure you assign only one value to the node affinity.`
specify machine family type based on architecture
https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning#custom_machine_family
=> bug: bundle build: node affinity only allows one value 

pkg/cli/build.go
This definitely shouldn't be doing anything given that all it does it return an error.
https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/gcp/gcp_stub.go
=> Drop gcp client-go plugin

main.go
We've been logging command errors as "INFO" with a verbose prefix and it's been bothering me!
```console
$ go run . adv ls --vuln blahasflkj               
2024/05/20 20:27:18 INFO error during command execution: no advisories repo dir specified, and distro auto-detection failed: directory is not a distro (packages) or advisories repository
```
```console
$ go run . adv ls --vuln blahasflkj
2024/05/20 20:31:11 ERRO no advisories repo dir specified, and distro auto-detection failed: directory is not a distro (packages) or advisories repository
```
=> fix: command errors are errors

pkg/cli/build.go, pkg/internal/bundle/bundle.go, pkg/tar/untar.go
Instead of just comparing hashes of bundle results, wolfictl build will now re-sign APKs with the signing key, regenerate each APKINDEX, and uploading both to a bucket given by --destination-bucket.
=> build: Re-sign, re-index, & upload bundle results

pkg/cli/build.go
This makes it clearer that a build failed because its dependency failed.
=> build: Show dep graph in errors

pkg/update/deps/cleanup.go
- **update: skip go/bump tidy without go.mod**
Sometimes package do odd things (manual git checkouts, git reset,
moving files about, patching them). When wolfictl update attemps to
update them, sometimes go/bump cleanups are not possible as go.mod is
not there after a plain git clone.
Instead of generating package update issue, still open a pull request
with version update. This issue was causing failure to update
cilium-1.15 like so:
> error cleaning up go/bump deps: unable to parse the go mod file with error: open /tmp/wolfibump3236022626/envoy/go.mod: no such file or directory
With this change in place a PR is still opened for package version &
expected-commit update.
See example of old cilium failure to update prior to this change xnox/os#2 and …
=> make go bump cleanup optional

go.mod, pkg/cli/build.go
This disables the otelhttp traces that the GCS client was emitting, which are probably useful but don't seem to respect the parent trace context, so they are just top level noise.
This also adds a "start <pkg>" trace to organize the "waiting for <dep>" traces under a reasonable parent instead of the root.
=> bundles: Make traces slightly more organized

pkg/internal/bundle/bundle.go
arm nodes have a max of 48 cores, set max cpu to 44 to avoid scheduling issues
this allows amd64 builds to go beyond 48 cores.
=> elastic: set max arm cpu value

pkg/cli/build.go, pkg/internal/bundle/bundle.go
Since task.Resources is shared between architectures, ovewriting these values in-place can cause a race.
=> bundles: Fix race in podspec generation

.github/workflows/golangci-lint.yaml, Makefile, go.mod, go.sum, pkg/cli/advisory_guide.go, pkg/cli/components/accept/accept.go, pkg/cli/components/advisory/field/text_field.go, pkg/cli/components/advisory/matchwatcher/model.go, pkg/cli/components/picker/picker.go
NB! As interactive styling is affected, somebody who uses those interactive modes should check that all styles/colors/bold are the still correct with these changes.
- **build(deps): bump github.com/charmbracelet/lipgloss**
Bumps [github.com/charmbracelet/lipgloss](https://github.com/charmbracelet/lipgloss) from 0.10.1-0.20240413172830-d0be07ea6b9c to 0.11.0.
- [Release notes](https://github.com/charmbracelet/lipgloss/releases)
- [Commits](https://github.com/charmbracelet/lipgloss/commits/v0.11.0)
---
updated-dependencies:
- dependency-name: github.com/charmbracelet/lipgloss
dependency-type: direct:production
update-type: version-update:semver-minor
...
Signed-off-by: dependabot[bot] <support@github.com>
- **Upgrade golangci-lint to latest**
Signed-off-by: Dimitri John Ledkov …
=> upgrade lipgloss

go.mod, go.sum
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@chainguard.dev>
Needs:
- https://github.com/wolfi-dev/os/pull/20407
- https://github.com/wolfi-dev/os/pull/20408
=> go: upgrade melange from v0.8.1 to v0.8.3

pkg/cli/bundle.go, pkg/internal/bundle/bundle.go
Originally attempted to do this by just shelling out to git for each file individually. For a small number of recently modified files, this isn't too bad, but for build-the-world builds, this ends up taking a very long time because we have to traverse the commit graph for each melange config, which is 2400 times, and that can take ~1s per file.
Instead, we traverse the commit graph once by shelling out to git and just parsing the output for every changed file per non-merge commit.
This takes about 2s on my machine, whereas doing it once per file took about 20 minutes.
=> bundles: Embed build date epoch in bundles

pkg/cli/lint.go, pkg/lint/linter.go, pkg/lint/linter_test.go, pkg/lint/rules.go, pkg/lint/rules_test.go, pkg/lint/testdata/files/has-subpackage-test.yaml, pkg/lint/testdata/files/no-main-test.yaml, pkg/lint/testdata/files/nolint.yaml, pkg/lint/types.go
adds a `minimum-severity` to the existing linter.
The new behavior allows for configuring the minimum severity tolerance that will flag an error (non-zero exit code) on a lint.
The default setting is to flag on `warning` and `error`, ignoring (but still logging) `info` severities.
To accommodate the new default behavior, the existing `INFO` rules are changed to `WARN`. The only one of these that's modified is the copyright header rule.
Finally, this adds a new `INFO` rule that enforces tests exist. The idea here is to make this a non-blocking lint rule.
=> add minimum severity to linter

pkg/cli/apk.go
These now work:
Index from file:
```
$ go run ./ apk cp go-1.22 -i=file://./packages/x86_64/APKINDEX.tar.gz  
2024/05/29 20:30:34 INFO downloading 1 packages for x86_64
2024/05/29 20:30:34 INFO skipping packages/x86_64/go-1.22-1.22.3-r0.apk: already exists
2024/05/29 20:30:38 INFO writing index: packages/x86_64/APKINDEX.tar.gz (3 total packages)
```
Index from stdin:
```
$ cat ./packages/x86_64/APKINDEX.tar.gz| go run ./ apk cp go-1.22 -i=-
2024/05/29 20:29:42 INFO downloading 1 packages for x86_64
2024/05/29 20:29:42 INFO skipping packages/x86_64/go-1.22-1.22.3-r0.apk: already exists
2024/05/29 20:29:46 INFO writing index: packages/x86_64/APKINDEX.tar.gz (3 total packages)
```
Index from HTTP with `apk`-compatible auth:
```
$ HTTP_AUTH=basic::user:pass go run ./ apk cp go-1.22
Error: GET …
```
=> apk cp: support HTTP_AUTH, index from stdin, index from file

pkg/cli/bundle.go
Seeing weird things in epoch computation, this might help.
=> bundle: Wire up stderr to git subcmd

go.mod, go.sum
// Pull in a fix for an unpatched CVE. mholt/archiver appears inactive/unmaintained.
replace github.com/mholt/archiver/v3 => github.com/anchore/archiver/v3 v3.5.2
=> stop using unmaintained dep github.com/mholt/archiver/v3 with CVE-2024-0406

pkg/sbom/sbom.go
Fixes #355 
This provides better parity with actual Syft and Grype scans, since "binary" packages owned by the APK package are removed when the `ExcludeBinaryPackagesWithFileOwnershipOverlap` option is enabled.
cc: @hectorj2f @cpanato 
Re: **tests**: We'll add integration tests to verify this behavior in another PR that conveniently I'm working on at the moment!
This updates the behavior for both SBOM generation and vulnerability scanning:
```console
go run . sbom --disable-sbom-cache ./packages/x86_64/openssl-3.3.0-r9.apk
🔎 Scanning "./packages/x86_64/openssl-3.3.0-r9.apk"
├── 📄 /.PKGINFO
│       📦 openssl 3.3.0-r9 (apk)
│
└── 📄 /usr/bin/openssl
📦 openssl 3.3.0 (binary)
```
```console
$ go run . sbom --disable-sbom-cache ./packages/x86_64/openssl-3.3.0-r9.apk    
🔎 Scanning …
```
=> fix(sbom,scan): binary package filtering

pkg/cli/text.go, pkg/dag/packages.go
This shaves off about a second for a lot of wolfictl commands when run against wolfi with a reasonably sized machine.
There's more we can do but this is an easy win.
Before:
```
make list-yaml  5.01s user 0.43s system 98% cpu 5.545 total
```
After:
```
make list-yaml  5.41s user 0.73s system 145% cpu 4.230 total
```
=> Parse configs in parallel in NewPackages

pkg/checks/diff.go, pkg/checks/diff_test.go
This test was failing locally and it turns out we were doing some things to make it pretty hard to diagnose:
1. We need to use `require.NoError` instead of `assert.NoError` if any subsequent test steps depend on there not being an error. Otherwise the "real" error gets overwritten with less helpful errors.
2. We had a bare `err` returned after executing `bincapz`, so the failure reason was being swallowed. In this case a new `-min-file-level` flag had been added that wasn't available in the binary in the local environment.
A good follow-up task would be to provide tests that account for the changes in #725, and ideally make the interaction with `bincapz` less side-effectful.
=> Fix Diff test and bincapz usage

pkg/update/deps/cleanup_test.go
We've started segmenting our Go tests into 2 tiers: `unit` and `integration`. This helps us maintain a fast feedback loop for the majority of tests, while ensuring we still have the longer-running tests passing before PRs are merged.
This PR reclassifies the tests in `pkg/update/deps/cleanup_test.go` as "integration" since they do extensive I/O and take a long time to run.
**Before:**
This file's tests alone took up ~70% of the entire unit test suite's run length.
```
--- PASS: TestCleanupDeps (22.07s)
```
**After:**
The **_entire_** unit test suite (see `make unit`) runs in just **~6 seconds**, and closer to ~1 second when using Go's test cache.
cc: @jonjohnsonjr
=> test: move Cleanup tests to integration tier

pkg/advisory/export.go, pkg/advisory/export_test.go, pkg/advisory/osv.go, pkg/cli/advisory.go, pkg/cli/advisory_export.go, pkg/cli/advisory_osv.go
This is a relatively straightforward separation of the OSV dataset build logic from the existing `export` command.
The `export` command is marked **experimental** and not designed to be load-bearing.
Meanwhile, we intend for our OSV output to be a **first-class, production-ized output**, on par with our `secdb` generation, which also has its own command and implementation (distinct from `export`).
This PR establishes a new entrypoint for OSV dataset builds: `wolfictl adv osv`. The core implementation logic has not been modified yet.
cc: @imjasonh @cpanato
=> refactor: separate OSV build from export command

pkg/scan/apk.go
To match Grype default behaviour, we need to set AllowMainModulePseudoVersionComparison to `false`.
=> Disable AllowMainModulePseudoVersionComparison by default

pkg/advisory/osv.go, pkg/advisory/osv_test.go, pkg/advisory/testdata/osv/expected/CGA-37qj-pjrf-fmrw.json, pkg/advisory/testdata/osv/expected/CGA-4j8r-gcwr-9w6v.json, pkg/advisory/testdata/osv/expected/CGA-4wr7-3v5h-hr26.json, pkg/advisory/testdata/osv/expected/CGA-5f5c-53mg-6p2v.json, pkg/advisory/testdata/osv/expected/CGA-5g25-7735-97mh.json, pkg/advisory/testdata/osv/expected/CGA-5x4g-4gp8-3frx.json, pkg/advisory/testdata/osv/expected/CGA-6mjr-v678-c6gm.json, pkg/advisory/testdata/osv/expected/CGA-7jpc-77v9-8xwj.json, pkg/advisory/testdata/osv/expected/CGA-7p3g-p2r2-p42c.json, pkg/advisory/testdata/osv/expected/CGA-7w75-jqq5-8pj3.json, pkg/advisory/testdata/osv/expected/CGA-c6mv-x33h-2rw7.json, pkg/advisory/testdata/osv/expected/CGA-fc7r-gjw8-c4xp.json, pkg/advisory/testdata/osv/expected/CGA-fpww-5q32-3pf7.json, pkg/advisory/testdata/osv/expected/CGA-fv8r-8vjj-mgx6.json, pkg/advisory/testdata/osv/expected/CGA-gg4h-ppqq-vf35.json, pkg/advisory/testdata/osv/expected/CGA-grqc-5h6x-rch8.json, pkg/advisory/testdata/osv/expected/CGA-gwv4-h62f-5frj.json, pkg/advisory/testdata/osv/expected/CGA-j59r-vcf2-x9p7.json, pkg/advisory/testdata/osv/expected/CGA-mm7m-x6cw-5fg4.json, pkg/advisory/testdata/osv/expected/CGA-mpmv-pqf6-j3w9.json, pkg/advisory/testdata/osv/expected/CGA-mpp5-xvx9-xj5q.json, pkg/advisory/testdata/osv/expected/CGA-vj68-6p3f-8xmr.json, pkg/advisory/testdata/osv/expected/all.json
Most of this PR is just adjusting the OSV JSON files to be multiline and indented. The main motivation for this was making it easier to see diffs in testing, and to make diffs easier to understand when they're introduced by PRs. But I implemented this by just changing how we format our OSV JSON always.
If this seems bad for some reason, please let me know, and we can discuss making the indented-form for testing only and not how we encode actual OSV data. cc: @cpanato 
This adds an `-update` flag to the OSV tests to make it easier to update the golden files when needed.
This also refactors some of the OSV build implementation and its test.
=> Indent JSON for OSV and improve tests

pkg/private/bundle/bundle.go
when we appended toleration previously, we gave it a choice to choose either `bundle-builder` or `gvisor-builder`
if we override, we force it to run on `gvisor-builder`
this remove the need for node selector
examining the taints on the node, there was a gvisor one we needed to add tolerations for
```
Taints:             chainguard.dev/runner=gvisor-builder:NoSchedule
sandbox.gke.io/runtime=gvisor:NoSchedule
DeletionCandidateOfClusterAutoscaler=1719031907:PreferNoSchedule
```
=> elastic build: override toleration rather than append for gvisor

go.mod, go.sum
Notable:
* Use current user's ID when building via Docker https://github.com/chainguard-dev/melange/pull/1298
* Make running the git-checkout via melange not emit WARN messages.
* feat - add flag to go/build to run go mod tidy https://github.com/chainguard-dev/melange/pull/1303
* enforce some more lint checks
* Add git-cherry-pick pipeline https://github.com/chainguard-dev/melange/pull/1278
=> Pick up several fixes from melange.

pkg/cli/build.go, pkg/cli/bundle.go
- make outdir config Public; needed to override where local packages stored
- make error more descriptive; for easier tracing where did the error come from
- added logic to construct kubeconfig based on input config rather than using env kubeconfig
=> add support to perform elastic build as lib from cloud run

pkg/cli/advisory_guide.go
This is a case where we really do not want logging — It's running the scanning code to supplement a terminal UX, not as a service.
=> fix(adv/guide): no context-based logging

pkg/cli/advisory_guide.go
Previously, impactful problems (e.g. we couldn't push the users changes to GitHub so we just deleted them) were getting swallowed as we unpacked the bubbletea model, so the app exited `0` with no explanation.
=> fix(adv/guide): let err bubble to user

pkg/configs/entry.go, pkg/configs/index.go, pkg/configs/selection.go, pkg/configs/yaml.go
Consumers of a `configs.Entry` need an easy way to access the file path that backs any given configuration document.
This also helps make it easier to implement features like in #1034.
cc: @Dentrax
=> export Path method on configs Entry

.github/dependabot.yml
```
Dependabot requires a .yml to evaluate your GitHub Actions dependencies. It had expected to find one at the path: /actions/<anything>.yml.
```
=> fix github-actions directory for dependabot

pkg/advisory/osv.go, pkg/advisory/testdata/osv/expected/CGA-37qj-pjrf-fmrw.json, pkg/advisory/testdata/osv/expected/CGA-5f5c-53mg-6p2v.json, pkg/advisory/testdata/osv/expected/CGA-6mjr-v678-c6gm.json, pkg/advisory/testdata/osv/expected/CGA-gg4h-ppqq-vf35.json, pkg/advisory/testdata/osv/expected/CGA-mm7m-x6cw-5fg4.json, pkg/advisory/testdata/osv/expected/CGA-vj68-6p3f-8xmr.json
See https://github.com/google/osv.dev/issues/2374 for motivation.
cc: @cpanato
=> fix(osv): move aliases to related field

pkg/checks/diff.go
In v0.14.0, bincapz now includes a new flag to disable marking files as CRITICALs whenever four or more file behaviours  have been marked as HIGHs.
=> chore: add new bincapz flag

pkg/cli/build.go, pkg/cli/bundle.go
The path for each build returns by walking packages is not relative to input when given an absolute filepath, and changing what's returned breaks a lot of other things, so we re-relativize the build config paths to be relative to --dir so that the bundle generated is independent of where the command is run (so you can clone a directory to a tmpdir or something).
We had a similar issue with shelling out to `git` which this also resolves.
=> bundle: Fix bundling when --dir != .

pkg/cli/lint.go
If errors only contain warnings, treat this as a success.
=> lint: Only fail command if error is returned.

go.mod, go.sum
Bump melange to pick up Ruby SCA changes
=> chore: Bump melange to v0.11.1

go.mod, go.sum
Contains an additional Ruby SCA change
=> chore: Bump melange to v0.11.2

pkg/checks/diff.go, pkg/checks/so_name.go, pkg/melange/melange.go
I noticed that we're using `filepath.Walk` in a few places when running `wolfictl check diff`. This PR swaps to `WalkDir` instead since `WalkDir` is [more efficient](https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/path/filepath/path.go;l=553-554) than `Walk`.
`make test` passes with these changes and the hope is that it helps somewhat with long-running diffs for numerous files as seen here with Keycloak: https://github.com/wolfi-dev/os/actions/runs/10009779412/job/27673386164?pr=24126
If there's a reason we need `Walk` that I'm not aware of please feel free to point that out!
=> Use filepath.WalkDir instead of filepath.Walk

pkg/sbom/catalogers/angularjs.go, pkg/sbom/catalogers/angularjs_test.go, pkg/sbom/catalogers/testdata/angular-resource.min.js, pkg/sbom/catalogers/testdata/angular.min.js, pkg/sbom/sbom.go
This PR adds a custom Syft cataloger to wolfictl. The new cataloger is designed to find instances of AngularJS (the deprecated project) in singular JS files, where there's limited "package" metadata available.
This new cataloger helps us find vulnerabilities that we're otherwise not detecting.
Once we're happy with the SCA strategy here, we can consider upstream-ing the cataloger to Syft, too.
Example:
```console
$ wolfictl scan ~/tmp/solr-9.6.1-r0.apk --disable-sbom-cache
🔎 Scanning "/Users/dan/tmp/solr-9.6.1-r0.apk"
└── 📄 /usr/share/java/solr/server/solr-webapp/webapp/libs/angular.min.js
📦 angular v1.8.0 (js-file)
Medium CVE-2021-4231
High CVE-2022-25844
Medium CVE-2022-25869
Medium CVE-2023-26116
Medium CVE-2023-26117
Medium CVE-2023-26118
High CVE-2024-21490
Medium CVE-2023-26117 …
```
=> feat(sbom): detect angularjs from minified files

pkg/private/bundle/bundle.go
once the deadline is reached, the pod will be marked as fail and container will be killed
this is to avoid stuck pods hanging around
=> set active deadline seconds to pod for elastic build pod

pkg/cli/build.go, pkg/cli/bundle.go
- move some spammy logs to debug
- ensure the namespace exists before trying to create pods there
- log the error when a task fails
=> build: various minor improvements

pkg/cli/build.go, pkg/cli/bundle.go, pkg/private/bundle/bundle.go
- embue logs with `pkg`, `pkgver` and `arch`
- attempt to surface build/test failures using termination logs -- if this is successful we can add more useful context here in the future
- move some spammy things to log.Debugf
=> build: improve logging

pkg/sbom/catalogers/python.go, pkg/sbom/catalogers/python_test.go, pkg/sbom/catalogers/testdata/bad/pip/_vendor/vendor.txt, pkg/sbom/catalogers/testdata/pip/_vendor/vendor.txt, pkg/sbom/sbom.go
Before:
```
wolfictl scan --disable-sbom-cache ./py3.12-pip-base-24.1.2-r1.apk
🔎 Scanning "./py3.12-pip-base-24.1.2-r1.apk"
```
After:
```
wolfictl scan --disable-sbom-cache ./py3.12-pip-base-24.1.2-r1.apk
🔎 Scanning "./py3.12-pip-base-24.1.2-r1.apk"
└── 📄 /usr/lib/python3.12/site-packages/pip/_vendor/vendor.txt
📦 urllib3 1.26.18 (pip-vendor-file)
Medium CVE-2024-37891
```
=> Add pip vendor cataloger

pkg/scan/filter_test.go, pkg/scan/finding.go, pkg/scan/testdata/goldenfiles/aarch64/crane-0.14.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/go-1.21-1.21.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/openjdk-10-jre-10.0.2-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/openssl-3.3.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/python-3.11-3.11.1-r5.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/terraform-1.3.9-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/thanos-0.32-0.32.5-r4.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/crane-0.14.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/go-1.21-1.21.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/openjdk-10-jre-10.0.2-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/openssl-3.3.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/python-3.11-3.11.1-r5.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/terraform-1.3.9-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/thanos-0.32-0.32.5-r4.apk.wolfictl-scan.json
We are adding support for java CVE remediation in our automation. Whenever I get the info from a vulnerability I only get the artifact ID (as PackageName) but I don’t get the group ID required by our tool pombump to upgrade dependencies in maven. 
PURL value in the packages includes this information, so we could propagate the purl value into our package findings, and thus extract it in our cve remediation services.
=> chore: add purl to the package findings

pkg/sbom/cpe.go, pkg/sbom/sbom.go, pkg/sbom/testdata/goldenfiles/aarch64/jenkins-2.461-r0.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/openjdk-21-21.0.3-r3.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/jenkins-2.461-r0.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/openjdk-21-21.0.3-r3.apk.syft.json
This imports the CPE mappings we had used in the NVD API detector mechanism, and extends the list with net new mappings as well. This helps us avoid depending too much on the Syft (non-dictionary) CPE generation mechanism, which tends to miss valid matches altogether.
The goal here is to further reduce our false negatives by ensuring more precise CPEs are used for APK package matching when possible.
```console
$ wolfictl sbom -D ./x86_64/libtasn1-4.19.0-r3.apk -o syft-json | jq '.artifacts[0].cpes'
[
{
"cpe": "cpe:2.3:a:libtasn1:libtasn1:4.19.0-r3:*:*:*:*:*:*:*",
"source": "syft-generated"
},
{
"cpe": "cpe:2.3:a:libtasn1:libtasn:4.19.0-r3:*:*:*:*:*:*:*",
"source": "syft-generated"
},
{
"cpe": "cpe:2.3:a:libtasn:libtasn1:4.19.0-r3:*:*:*:*:*:*:*",
"source": "syft-generated"
},
{
"cpe": …
```
=> feat(sbom,scan): better CPE coverage for APK packages

pkg/advisory/create.go, pkg/advisory/create_test.go, pkg/advisory/data_session.go, pkg/advisory/discover.go, pkg/advisory/request.go, pkg/advisory/testdata/create/advisories/brotli.advisories.yaml, pkg/advisory/update.go, pkg/advisory/update_test.go, pkg/cli/advisory.go, pkg/cli/advisory_alias_find.go, pkg/cli/advisory_create.go, pkg/cli/advisory_guide.go, pkg/cli/advisory_guide_graph.go, pkg/cli/advisory_update.go, pkg/cli/components/advisory/prompt/model.go, pkg/configs/advisory/v2/advisory.go, pkg/configs/advisory/v2/document.go
The advisory request API has been straightened out, following the introduction of CGA IDs. The `VulnerabilityID` field has been renamed to `AdvisoryID` to clarify its intent (that it **must** be one of our `CGA-...` IDs, not a CVE ID or GHSA ID). It can be set during advisory update operations in order to specify an advisory by CGA ID, otherwise the aliases of the request are used. For create operations, the `AdvisoryID` field must be empty, since CGA IDs will be generated on the fly. This fixes #1086.
Additionally (but relatedly), alias resolution is now allowed to fail during the `guide` command. This fixes #1083.
This also resolves an issue where the user specified a vulnerability with the `-V` flag on either the `create` or `update` command and was still prompted for the vulnerability …
=> fix(adv)!: untangle advisory request ID expectations

pkg/melange/melange.go
This func is commonly pulled in to other utilities. Printing to stdout can taint output. This doesn't seem like a critical log line, so instead of moving to stderr, remove the line completely.
=> Remove print from ReadAllPackagesFromRepo.

Makefile, pkg/cli/commands.go, pkg/cli/internal/wrapped/wrapped.go, pkg/tar/untar.go
New `gosec` findings coming up — this addresses them.
This also bumps the version of `golangci-lint` used in `make lint`.
=> Lint fixing

pkg/cli/advisory.go, pkg/cli/advisory_id.go
Example:
```console
$ wolfictl adv id
CGA-8g8r-m7fc-3g76
$ wolfictl adv id
CGA-vqh9-w5mj-qm34
$ wolfictl adv id
CGA-59px-x9c3-rhhm
$ wolfictl adv id
CGA-gfg2-hgp7-848j
```
=> feat(adv): command to generate a new CGA ID

pkg/lint/rules.go, pkg/lint/rules_test.go
the  lint checks are [failing](https://github.com/chainguard-dev/enterprise-packages/actions/runs/10679086822/job/29601804690) for update sections with git monitors 
```
update:
enabled: true
ignore-regex-patterns:
- sdks/
- '-RC'
git:
strip-prefix: v
```
=> dont flag git updates as errors

pkg/advisory/validate.go, pkg/advisory/validate_test.go
As per conversation with @luhring, We agree that the stringent rule of the fixed version of a package can not be the first version should be relaxed and addressed more methodically moving forward. An example of where this is in the instance where validation is recommending to change previously valid fix version tags [to 'false-positive-determination'](https://github.com/chainguard-dev/enterprise-advisories/actions/runs/10622587699/job/29447212893#step:7:27) due to the commit history being lost when the package file was deleted and remade.
=> Removing fixed-version-present-and-first logic and test

pkg/cli/dot.go, pkg/dag/graph.go, pkg/dag/graph_test.go, pkg/dag/testdata/duplicate/one-dupl.yaml, pkg/dag/testdata/multiple/one.yaml
We were only looking at main package runtime deps when constructing the dependency graph, which meant we missed a lot of edges that were very important.
=> Consider subpackage runtime deps for graph

pkg/dag/graph.go
This happens often with version streams that have packages with the exact same name, so my assumption that a given package belongs to a single origin is wrong. The existing error message complains about cycles in the graph, which is misleading.
=> Improve error message for duplicate package names

pkg/dag/graph.go
Previously we just failed with an error that a cycle exists, which is not helpful. Now we include the entire cycle in the error for debugging.
=> Report cycles better when calling Targets

pkg/checks/diff.go
This PR updates `bincapz` references to `malcontent`.
Depends on:
- https://github.com/wolfi-dev/os/pull/29171
- https://github.com/wolfi-dev/tools/pull/149
=> Rename bincapz to malcontent

pkg/git/git_test.go
I noticed this started failing for me, seemingly out the blue, but it was from a change in my local environment. This PR isolates the env variable used in the test from whatever the developer has in their environment.
=> fix(git): test flaking from env side effects

pkg/cli/commands.go
Fixes #1208.
We'll be able to remove this bit of code altogether once we update to a new version of charm log.
```console
$ go run . adv alias find --log-level debug CVE-2024-1111
2024/09/25 08:23:02 ERROR log level out of range: -4
exit status 1
```
```console
$ go run . adv alias find --log-level debug CVE-2024-1111
Aliases for CVE-2024-1111:
- GHSA-9m6f-83hx-8wwr
```
_Note there is no DEBUG-level logging for `wolfictl adv alias find`._
=> fix(log): correct int32 bounds checking

pkg/cli/scan.go
This lets us reuse this from some internal services.
=> scan: export FindingsTree and Render

pkg/sbom/cpe.go
Ensures we find openssl CVEs for the FIPS provider by explicitly setting the package CPE.
```console
$ wolfictl scan -D ./openssl-provider-fips-3.0.9-r1.apk
🔎 Scanning "./openssl-provider-fips-3.0.9-r1.apk"
```
```console
$ wolfictl scan -D ./openssl-provider-fips-3.0.9-r1.apk
🔎 Scanning "./openssl-provider-fips-3.0.9-r1.apk"
└── 📄 /.PKGINFO
📦 openssl-provider-fips 3.0.9-r1 (apk)
Medium CVE-2023-2975
Medium CVE-2023-3817
High CVE-2023-4807
High CVE-2023-5363
Medium CVE-2023-5678
Medium CVE-2023-6129
Unknown CVE-2023-6237
Medium CVE-2024-0727
Unknown CVE-2024-2511
Medium CVE-2024-4603
Critical CVE-2024-5535
High CVE-2024-6119
```
=> fix(sbom,scan): find openssl CVEs for FIPS provider

pkg/checks/diff.go
This PR corrects the `exec.LookPath` when looking for `malcontent` which is installed as `mal` in the SDK image:
```
/ # mal --help
NAME:
malcontent - Detect malicious program behaviors
USAGE:
mal <flags> [diff, scan] <path>
VERSION:
v1.0.1
COMMANDS:
analyze  fully interrogate a path
diff     scan and diff two paths
scan     tersely scan a path and return findings of the highest severity
help, h  Shows a list of commands or help for one command
GLOBAL OPTIONS:
--all                      Ignore nothing within a provided scan path (default: false)
--err-first-miss           Exit with error if scan source has no matching capabilities (default: false)
--err-first-hit            Exit with error if scan source has matching capabilities (default: false)
--format value             Output format …
```
=> Fix exec.LookPath for malcontent

pkg/sbom/cpe.go
We've been missing CVEs in GitLab. For NVD data, GitLab has a CPE of: `cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:* `.
Syft has been generating lots of CPEs for GitLab components, but they're never correct. For example:
```json
{
"cpe": "cpe:2.3:a:gitlab_logger:gitlab-logger:17.4.0-r2:*:*:*:*:*:*:*",
"source": "syft-generated"
},
{
"cpe": "cpe:2.3:a:gitlab_logger:gitlab_logger:17.4.0-r2:*:*:*:*:*:*:*",
"source": "syft-generated"
},
{
"cpe": "cpe:2.3:a:gitlab:gitlab-logger-17.4:17.4.0-r2:*:*:*:*:*:*:*",
"source": "syft-generated"
},
{
"cpe": "cpe:2.3:a:gitlab:gitlab_logger_17.4:17.4.0-r2:*:*:*:*:*:*:*",
"source": "syft-generated"
},
{
"cpe": "cpe:2.3:a:gitlab:gitlab-logger:17.4.0-r2:*:*:*:*:*:*:*",
"source": "syft-generated"
},
{
"cpe": "cpe:2.3:a:gitlab:gitlab_logger:17.4.0-r2:*:*:*:*:*:*:*", …
```
=> fix(scan): use correct CPE for GitLab components

pkg/checks/diff.go
`malcontent` v1.2.0 added new `diff` flags that should help cut down on the noise in PRs.
This PR updates the flags `wolfictl` uses for diffs.
=> Update malcontent diff flags

pkg/checks/diff.go
The new file risk flags are flags for the `diff` command rather than global flags:
```
$ go run cmd/mal/mal.go diff -h
NAME:
malcontent diff - scan and diff two paths
USAGE:
malcontent diff [command options]
OPTIONS:
--file-risk-change    Only show diffs when file risk changes (default: false)
--file-risk-increase  Only show diffs when file risk increases (default: false)
--help, -h            show help
```
=> Move file-risk-increase flag under diff command

pkg/dag/graph.go
If we try to resolve a dependency that just doesn't exist in any of our sources, we currently get a horribly misleading error mentioning cycles that doesn't actually make any sense.
This makes sure we have some candidates first.
=> text: Improve err for missing packages

pkg/cli/check_so_name.go
This was refactored out in https://github.com/wolfi-dev/wolfictl/pull/1296 and wasn't populated with the flag value, so all checks were failing.
=> check so-name: fix error with apk index URL

.github/workflows/golangci-lint.yaml, Makefile, pkg/advisory/export.go, pkg/advisory/secdb.go, pkg/cli/components/interview/interview.go, pkg/cli/dot.go
This PR addresses a handful of items with regarding to how we **lint** the project:
1. It's really important to have parity between local dev checks and CI checks. Our `make lint` target was using a different version of golangci-lint than our CI was, and thus you couldn't anticipate CI's results by using `make lint`. This brings them into parity.
2. Bumps golangci-lint to the most recent version, v1.62.
3. Removes the `-n` flag from the `make lint` execution of `golangci-lint`, which was suppressing existing lint errors. The suppressed errors were coming from the `errcheck` linter, calling out type assertions without an explicit check (i.e. with `..., ok := something.(some_type)`).
=> Several linting improvements

pkg/cli/advisory.go, pkg/cli/advisory_create.go, pkg/cli/advisory_update.go
This adds a new `--note` flag that can be used to specify the `note` field of the new advisory event, for any event type that needs a note specified. This proposes that `--note` could eventually replace event-type-specific flags like `--fp-note` and `--tp-note`.
The following event types are now supported with `--note`: `pending-upstream-fix`, `analysis-not-planned`, `fix-not-planned`. For true and false positives, the type-specific flag takes priority over `--note`.
These type-specific flags have also been deprecated and will be removed in a future release.
Previously, when distro auto-detection was disabled explicitly via the CLI flag, the `packageRepositoryURL` value wasn't checked ahead of time, so bogus requests were made for the APKINDEX and an opaque error was reported to the user. …
=> Enhance scriptability of advisory `create` and `update` commands

pkg/cli/advisory_list.go, pkg/cli/scan.go
Adds terminal hyperlinking to CGA IDs — now that we have CGA-specific pages on Chainguard's web console! 🚀
=> feat: add web hyperlinks to CGA IDs

pkg/cli/components/scanfindings/scanfindings.go, pkg/cli/components/tree/tree.go, pkg/cli/components/tree/tree_test.go, pkg/cli/components/vulnid/vulnid.go, pkg/cli/scan.go, pkg/scan/finding.go
The mission of this PR is to generalize the tree rendering logic we've used in `wolfictl scan`, `wolfictl sbom`, and other consumers of this code, so that we have a central way to render these trees, and can adjust aspects of rendering as needed for future enhancements.
The updated tree rendering implementation is now used by `wolfictl scan`. (Later we'll also use this for `wolfictl sbom`.) But the old tree rendering is left in place since it is exported and used elsewhere. It will be removed in a follow-up PR.
A guiding principle is that we don't want to export logic directly from the `cli` package. But the `cli/components` package is more appropriate for exporting and reuse.
=> refactor: introduce general tree output rendering

pkg/advisory/request.go, pkg/advisory/request_test.go, pkg/cli/components/advisory/prompt/model.go
This PR adds validation to ensure CGA IDs can't be used as aliases, and it fixes an issue with the interactive prompts where the `Vulnerability: ` prompt value was being stored as an alias.
=> fix(adv): ensure CGA IDs can be specified as the "vulnerability" in prompts without ending up as an alias

pkg/cli/components/scanfindings/scanfindings.go, pkg/cli/scan.go, pkg/cli/styles/styles.go, pkg/configs/advisory/v2/event.go, pkg/scan/finding.go, pkg/scan/testdata/goldenfiles/aarch64/crane-0.14.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/go-1.21-1.21.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/openjdk-10-jre-10.0.2-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/openssl-3.3.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/python-3.11-3.11.1-r5.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/terraform-1.3.9-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/thanos-0.32-0.32.5-r4.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/crane-0.14.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/go-1.21-1.21.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/openjdk-10-jre-10.0.2-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/openssl-3.3.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/python-3.11-3.11.1-r5.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/terraform-1.3.9-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/thanos-0.32-0.32.5-r4.apk.wolfictl-scan.json
For each vulnerability match, if user has provided advisory data (using `-a` / `--advisories-repo-dir`), show the latest status from the applicable advisory.
This PR also deprecates the logic used for experimental triaging using govulncheck.
cc: @philroche
=> feat(scan): show context from advisory data

pkg/cli/components/sbompackages/sbompackages.go, pkg/cli/components/scanfindings/scanfindings.go, pkg/cli/sbom.go
Also clean up styles used in `scanfindings` component.
=> Re-use central tree component for SBOM package rendering

pkg/cli/image_apk.go
```bash
$ ./wolfictl image apk cgr.dev/chainguard/wolfi-base:latest
apk-tools (2.14.4-r1)
busybox (1.37.0-r0)
ca-certificates-bundle (20241010-r2)
glibc (2.40-r3)
glibc-locale-posix (2.40-r3)
ld-linux (2.40-r3)
libcrypt1 (2.40-r3)
libcrypto3 (3.4.0-r2)
libgcc (14.2.0-r6)
libssl3 (3.4.0-r2)
libxcrypt (4.4.36-r8)
wolfi-base (1-r6)
wolfi-baselayout (20230201-r15)
wolfi-keys (1-r8)
zlib (1.3.1-r4)
```
=> print full package version with image apk subcommand

pkg/cli/text.go, pkg/dag/packages.go
I was trying to locally replicate an error in CI, but I hadn't set up my local environment quite right.
Here's the error that `wolfictl` gave me:
```text
Error: stat .: no such file or directory
```
That was it. 😱 
Now, it turns out that the real issue was that in CI, we clone the Wolfi `os` directory to a local directory called `wolfi-os`, and I hadn't done that on my machine. But this was impossible to know from the error.
With this PR, the error now looks like:
```text
Error: constructing new packages set from directory "wolfi-os": walking filesystem: stat .: no such file or directory
```
=> fix(text): add context to dag construction error messages

pkg/cli/advisory_list.go, pkg/cli/scan.go, pkg/configs/advisory/v2/advisory.go, pkg/configs/advisory/v2/analysis_not_planned.go, pkg/configs/advisory/v2/detection.go, pkg/configs/advisory/v2/document.go, pkg/configs/advisory/v2/event.go, pkg/configs/advisory/v2/false_positive_determination.go, pkg/configs/advisory/v2/fix_not_planned.go, pkg/configs/advisory/v2/fixed.go, pkg/configs/advisory/v2/pending_upstream_fix.go, pkg/configs/advisory/v2/timestamp.go, pkg/configs/advisory/v2/true_positive_determination.go
The `adv ls` command is a nifty way to zoom into particular aspects of advisory data pretty quickly. The existing command rendered a terminal-friendly table, but the output is not really machine-readable.
This PR adds a new `--output`/`-o` flag, whose value defaults to `table` (the existing rendering mechanism), but where users can now pass `json` to produce machine-readable data from the `adv ls` query.
```console
$ wolfictl adv ls --type fp --updated-since 2024-11-20 -o json | jq
[
{
"schemaVersion": "2.0.2",
"package": {
"name": "akhq"
},
"advisories": [
{
"id": "CGA-2hmx-pc95-g53j",
"aliases": [
"CVE-2024-47535",
"GHSA-xq3w-v528-46rv"
],
"events": [
{
"timestamp": "2024-11-20T20:00:27Z",
"type": "false-positive-determination",
"data": {
"type": …
```
=> feat(adv): add `-o json` option to `adv ls` command

pkg/apk/apk.go
hashi's retryablehttp debug-logs every request, which is noisy and incompatible with `log/slog` (https://github.com/hashicorp/go-retryablehttp/issues/211), so let's just make it totally quiet until we can make it debug-quiet.
Before
```
go test ./pkg/apk -v -run=Test_getApkPackages
=== RUN   Test_getApkPackages
2025/01/08 09:20:59 [DEBUG] GET http://127.0.0.1:58527/APKINDEX.tar.gz
2025/01/08 09:20:59 found 2 latest apk index package versions
--- PASS: Test_getApkPackages (0.00s)
PASS
ok      github.com/wolfi-dev/wolfictl/pkg/apk   0.306s
```
After
```
go test ./pkg/apk -v -run=Test_getApkPackages
=== RUN   Test_getApkPackages
2025/01/08 09:20:52 found 2 latest apk index package versions
--- PASS: Test_getApkPackages (0.00s)
PASS
ok      github.com/wolfi-dev/wolfictl/pkg/apk   0.327s
```
=> pkg/apk: don't log requests

pkg/dag/graph.go
This makes it consistent with how apko and melange are using keys. We will follow up with a PR in apko to reject key with '/' in the name.
=> wolfictl: strip urls from key names when calling `apk.GetRepositoryIndexes`

docs/cmd/wolfictl_advisory_osv.md, docs/cmd/wolfictl_advisory_validate.md, docs/cmd/wolfictl_advisory_validate_fixes.md, docs/cmd/wolfictl_scan.md, docs/man/man1/wolfictl-advisory-osv.1, docs/man/man1/wolfictl-advisory-validate-fixes.1, docs/man/man1/wolfictl-advisory-validate.1, docs/man/man1/wolfictl-scan.1, pkg/cli/advisory.go, pkg/cli/advisory_osv.go, pkg/cli/advisory_validate.go, pkg/cli/advisory_validate_fixes.go, pkg/cli/sbom.go, pkg/cli/scan.go
This aligns wolfictl's debug-logging flag across all its commands to use `--log-level` and the top-level charmbracelet logger, instead of having different ones for certain commands.
=> remove --verbosity flag in favor of --log-level

go.mod, go.sum, pkg/cli/commands.go
https://github.com/charmbracelet/log/pull/141 is merged upstream but isn't released yet, so `go get log@main` to take advantage of it.
=> cleanup charm log indirection

go.mod, go.sum, pkg/scan/apk.go
We were seeing inconsistent scan results caused by rate limiting by maven central.
This change will
- track main/27bcc7a9e9e8 until https://github.com/anchore/grype/pull/2397 is released
- throttle requests to maven central at a rate of 1 request per 400ms for reliable results on large maven based packages
This has been tested on a wide range of wolfi packages.
=> scan: bump grype dependency until upstream releases, make use of new rate-limit config

pkg/sbom/cpe.go
This will help find CVEs for OpenJDK that apply too to corretto.
=> feat(sbom,scan): use openjdk CPE for corretto

pkg/sbom/sbom.go
With this change .apk which contain ELF package notes scan the same
way as they did before. This unblocks enabling ELF package notes,
whilst design on how to incorporate them into `wolfictl scan` can then
iterate on that at a later point.
```
$ ./wolfictl --log-level=debug  scan scanelf-1.3.8-r2.apk
2025/01/25 22:10:38 DEBU checking cache for SBOM expectedPath=/home/xnox/.cache/wolfictl/sbom/apk/scanelf-1.3.8-r2-sha256-8f340707e80c5a4159c41ef40ed6d3e2dc052f806b5cfbf906b1ade9b575ab14.syft.json
2025/01/25 22:10:38 DEBU SBOM cache miss cachedPath=/home/xnox/.cache/wolfictl/sbom/apk/scanelf-1.3.8-r2-sha256-8f340707e80c5a4159c41ef40ed6d3e2dc052f806b5cfbf906b1ade9b575ab14.syft.json
2025/01/25 22:10:38 INFO generating SBOM for APK file path=scanelf-1.3.8-r2.apk distroID=wolfi
2025/01/25 22:10:38 …
```
=> sbom: remove elf-package cataloger during .apk scan

pkg/anchorelog/slog_adapter.go, pkg/sbom/sbom.go, pkg/scan/apk.go
This creates an adapter from the `slog.Logger` we get from `clog` to the Anchore proprietary [go-logger interface](https://github.com/anchore/go-logger/blob/main/logger.go), so we can start picking up log activity from the underlying tasks of generating an SBOM and vulnerability matching (from syft and grype, respectively).
Here's a sample of the new kinds of logging available to us:
```
2025/02/11 08:26:57 DEBU used CPE dictionary to find CPEs for rust-crate package "tungstenite": [{cpe:2.3:a:snapview:tungstenite:0.24.0:*:*:*:*:rust:*:* nvd-cpe-dictionary}]
2025/02/11 08:26:57 DEBU used CPE dictionary to find CPEs for rust-crate package "wasmtime": [{cpe:2.3:a:bytecodealliance:wasmtime:24.0.2:*:*:*:*:rust:*:* nvd-cpe-dictionary}]
2025/02/11 08:26:57 DEBU used CPE dictionary to find CPEs …
```
=> feat(sbom,scan): wire up Anchore logging into our slog instance

pkg/advisory/testdata/diff/added-event-with-non-recent-timestamp/a/ko.advisories.yaml, pkg/advisory/testdata/diff/added-event-with-non-recent-timestamp/b/ko.advisories.yaml, pkg/advisory/validate.go
Per discussion with @powersj and @hbh7, this should be more accommodating of legitimate cases where advisory PRs are open for longer, without allowing knowably bad data to get added.
=> fix(adv): extend event max age from 3 to 30 days

pkg/sbom/pkginfo.go, pkg/sbom/sbom.go
Based on the work in melange: https://github.com/chainguard-dev/melange/pull/1768
```console
$ wolfictl sbom -D ../wolfi-os/packages/aarch64/cosign-2.4.3-r1.apk -o syft-json | jq '.artifacts | map(select(.type == "apk"))'          
[
{
"id": "faf1d6bb7e0fc4cc",
"name": "cosign",
"version": "2.4.3-r1",
"type": "apk",
"foundBy": "wolfictl",
// ...
"cpes": [
{
"cpe": "cpe:2.3:a:sigstore:cosign:2.4.3-r1:*:*:*:*:*:*:*",
"source": "melange-configuration"
}
],
```
The above was a cosign APK built with a Melange YAML of:
```yaml
package:
name: cosign
version: "2.4.3"
epoch: 1
description: Container Signing
copyright:
- license: Apache-2.0
cpe:
vendor: sigstore
product: cosign
```
The default behavior without adding CPE data to the Melange YAML, which is totally okay.
```console
$ wolfictl sbom -D …
```
=> feat(sbom,scan): leverage CPE data in melange configuration when available

pkg/sbom/sbom.go
I was overzealous in adding more log entries in https://github.com/wolfi-dev/wolfictl/pull/1469. We weren't expecting a non-nil value of c here, so I shouldn't have logged it!
=> fix: panic caused by extra log entry

pkg/sbom/sbom.go
This handles a warning that started showing up in Syft's logging recently, which was [put in place](https://github.com/anchore/syft/pull/3505) to make users aware that they were running with file catalogers turned on. This PR accepts the new cataloger explicitly, which removes the warning.
```console
$ wolfictl scan ~/apks/apko-0.25.1-r2.apk
2025/03/03 10:11:17 WARN adding 'file' tag to the default cataloger selection, to override add '-file' to the cataloger selection request
...
```
=> chore: silence file tag warning by adding it explicitly

pkg/sbom/cpe.go, pkg/sbom/sbom.go, pkg/sbom/testdata/goldenfiles/aarch64/terraform-1.5.7-r12.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/thanos-0.32-0.32.5-r4.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/terraform-1.5.7-r12.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/thanos-0.32-0.32.5-r4.apk.syft.json, pkg/scan/apk.go
With a goal of finding more true positives for the Go ecosystem, this PR turns on CPE matching for Go modules.
With this, we are also investing in better CPE assignments during SBOM generation, particularly for the `golang.org/x/...` group of repositories.
Also, since we're still using some Syft-generated CPEs, we've added a step at the end of matching to filter out CPE-based matches that don't meet our standards.
⚠️ Like all changes of this nature, it's possible this will produce unexpected false positives/negatives in our APK scans. However, since we're in control of everything we've just added, we should be able to quickly respond to any behavioral changes we don't like.
=> feat(sbom,scan): leverage CPE data for Go module matching

pkg/sbom/cpe.go, pkg/sbom/testdata/goldenfiles/aarch64/terraform-1.5.7-r12.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/thanos-0.32-0.32.5-r4.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/terraform-1.5.7-r12.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/thanos-0.32-0.32.5-r4.apk.syft.json
We're not aware of any misses so far because of these, but this will help us get our SBOMs ready for future CPE-based matches for these commonly used packages.
Reference: https://pkg.go.dev/golang.org/x/net
=> chore(sbom): add more package CPEs for golang.org/x/net

pkg/sbom/sbom.go, pkg/scan/apk.go, pkg/scan/apk_test.go
With Syft, each individual CPE in the SBOM is attributed to a source where that CPE value came from, which is really useful for deciding if/how to act upon that CPE during vulnerability matching.
This PR makes further adjustments to how CPE-based matches in the Go ecosystem are treated, specifically by requiring that the CPE used for the match came from a trusted source. By requiring this, we ensure a higher confidence in the vulnerability match before including it in the output results.
This is a follow-on to the work in #1475.
Trusted:
- `wolfictl`
- `melange-configuration`
- `nvd-cpe-dictionary`
Untrusted:
- `syft-generated`
=> fix(scan): Go matches must use trusted CPE sources

pkg/anchorelog/slog_adapter.go
This message is pretty spammy, and is more of a low-level concern within Syft than a noteworth business logic operation.
Downgrading this to DEBUG to make our service logs easier to read.
cc: @cpanato @rawlingsj (from this morning)
=> chore(sbom,scan): downgrade "task completed" messages to DEBUG

pkg/scan/apk.go
This PR temporarily disables Maven searches for java-archive packages. The reason for this is because in [v0.89.1 of Grype](https://github.com/anchore/grype/releases/tag/v0.89.1) these 403s rate limits are now surfaced as fatal errors, which would cause our scanning to fail as well.
=> config(scan/apk): disable maven searches until we resolve the 403 rate limit issues with the newer release of Grype

pkg/advisory/fs_getter.go, pkg/advisory/fs_getter_test.go, pkg/advisory/store.go, pkg/advisory/testdata/fs_getter/brotli.advisories.yaml, pkg/cli/advisory_list.go, pkg/configs/advisory/v2/document.go, pkg/configs/advisory/v2/document_test.go, pkg/configs/advisory/v2/index.go, pkg/configs/advisory/v2/package_advisory.go
- Begin new advisory interface design — using a `Store` abstraction, which will be decomposed into read (`Getter`) and write (name TBD) interfaces (since so many consumers' needs are read-only)
- Update `adv list` command to use advisory `Getter`
- Implement a simple `Getter` using `fs.FS` with just open and decode calls
=> feat(adv): introduce read-only abstraction, create a simple implementation, and use in `adv list` command

docs/cmd/wolfictl_advisory_create.md, docs/cmd/wolfictl_advisory_update.md, docs/man/man1/wolfictl-advisory-create.1, docs/man/man1/wolfictl-advisory-update.1, pkg/advisory/alias_finder.go, pkg/advisory/alias_finder_test.go, pkg/advisory/discover_aliases_test.go, pkg/advisory/request.go, pkg/advisory/request_test.go, pkg/advisory/store.go, pkg/cli/advisory.go, pkg/cli/advisory_create.go, pkg/cli/advisory_update.go, pkg/cli/components/advisory/field/field.go, pkg/cli/components/advisory/field/list_field.go, pkg/cli/components/advisory/field/text_field.go, pkg/cli/components/advisory/prompt/model.go
This updates the `wolfictl adv create` and `... update` commands to be able to handle updates of multiple packages and/or vulnerabilities in one fell swoop — both via the CLI flags and the interactive prompts.
You can specify more than one item for both packages and vulnerabilities using a comma-separated list, e.g.:
```console
wolfictl adv create -p apko,age -V CVE-2025-1111,CVE-2025-1112 -t fix-not-planned --note 'insert reason'
```
`wolfictl` handles this by applying the given advisory event parameters to the cross product of any listed packages and vulnerabilities. So in the above example, we'll create a new advisory with the `fix-not-planned` event, for two packages, and two vulnerabilities for each of those two packages — resulting in the creation of **4 new advisories total**.
Less …
=> feat(adv): bulk create and update of adv data

pkg/advisory/fs_putter.go, pkg/advisory/fs_putter_test.go, pkg/advisory/request.go, pkg/advisory/request_test.go, pkg/advisory/store.go, pkg/advisory/testdata/fs_putter/create-when-document-exists-but-not-advisory/foo.advisories.yaml, pkg/advisory/testdata/fs_putter/create-when-document-exists-but-not-advisory/foo_expected.advisories.yaml, pkg/advisory/testdata/fs_putter/create-when-no-document-exists/foo_expected.advisories.yaml, pkg/advisory/testdata/fs_putter/no-op-update/foo.advisories.yaml, pkg/advisory/testdata/fs_putter/no-op-update/foo_expected.advisories.yaml, pkg/advisory/testdata/fs_putter/package-name-with-nonexistent-advisory-ID/foo.advisories.yaml, pkg/advisory/testdata/fs_putter/package-name-with-nonexistent-advisory-ID/foo_expected.advisories.yaml, pkg/advisory/testdata/fs_putter/update/foo.advisories.yaml, pkg/advisory/testdata/fs_putter/update/foo_expected.advisories.yaml, pkg/cli/advisory.go, pkg/cli/advisory_create.go, pkg/cli/advisory_update.go, pkg/configs/rwfs/os/testerfs/fsys.go
This finishes documenting the new `advisory.Putter` write-only abstraction, and it creates an implementation that uses an (abstract) writeable filesystem so that we no longer need to use the hefty `configs.Index[v2.Document]` implementation in order to programmatically create and update advisories.
=> advisories: add `FSPutter` implementation, use this to replace `configs.Index[v2.Document]` in `adv create` and `adv update` commands

docs/cmd/wolfictl_advisory_create.md, docs/cmd/wolfictl_advisory_update.md, docs/man/man1/wolfictl-advisory-create.1, docs/man/man1/wolfictl-advisory-update.1, pkg/advisory/fs_getter.go, pkg/advisory/fs_putter_test.go, pkg/advisory/request.go, pkg/advisory/request_test.go, pkg/advisory/testdata/fs_putter/just-update-aliases/foo.advisories.yaml, pkg/advisory/testdata/fs_putter/just-update-aliases/foo_expected.advisories.yaml, pkg/cli/advisory.go, pkg/cli/advisory_create.go, pkg/cli/advisory_update.go
This was requested by the Sustaining team, to help ensure that if they're operating en masse on a set of advisories, bulk operations are resilient to the scenario where one or two of the advisories in the target set have already received their updates via some other mechanism. The command logs a warning when this happens, so the user knows that part of the requested update was skipped, in case they want to add an event to the skipped advisory after all.
This PR also catches up on the auto-gen'ed documentation.
=> feat(adv): on bulk operations for `create` and `update`, skip event additions that would be redundant by event type

go.mod, go.sum
Just to stay on latest. I don't see any changes in the release notes that seem directly applicable to us.
=> build(deps): bump grype to v0.91.0

pkg/cli/scan.go
Before we were only handling this for the outline output format. We don't want this to depend on the output format.
=> fix(scan): avoid panic by handling err from SBOM gen

pkg/scan/apk.go
When Anchore fails to build a DB on a given day, the 24 hour max age becomes too small for our ability to scan successfully. Increase to 48 hours to allow for more resilience without risking silently scanning with overly stale data.
=> fix(scan): increase allowed age for Grype DB

pkg/advisory/index_adapter.go, pkg/advisory/index_adapter_test.go, pkg/advisory/store.go, pkg/advisory/testdata/index_adapter/advisories/brotli.advisories.yaml, pkg/advisory/testdata/index_adapter/advisories/ko.advisories.yaml, pkg/advisory/testdata/index_adapter/advisories/openssl.advisories.yaml, pkg/advisory/utils.go, pkg/cli/advisory_guide.go, pkg/cli/scan.go, pkg/scan/filter.go, pkg/scan/filter_test.go, pkg/scan/testdata/advisories/ko.advisories.yaml
This also introduces a nifty mechanism for taking an existing, old-style `*configs.Index[v2.Document]` and adapting it to the new `advisory.Getter` interface so that consuming code can move ahead to the abstraction-based model when possible.
=> refactor(scan): update scan filtering to use new `advisory.Getter` abstraction

pkg/scan/filter.go, pkg/scan/testdata/advisories/foo.advisories.yaml
We noticed that filtering was accounting for all advisories, which unintentionally reduced the original result scan set.
For example, simply adding a new advisory file (e.g., under a new package name like `foo.advisories.yaml`) with matching vulnerability aliases would cause existing tests to fail. This happened because `advGetter.PackageNames` was collecting all advisories (e.g., from wolfi-dev/advisories) and applying them during filtering.
However, the correct behavior appears to be filter only using advisories that match the incoming `result.TargetAPK.Name` OR `result.TargetAPK.OriginPackageName` (to account for subpackages).
@luhring thoughts?
=> bug(scan/filter): filtering considered all advisories and not just the target package

pkg/advisory/index_adapter.go, pkg/scan/filter.go, pkg/scan/filter_test.go
This is related to one issue with the scanning of apks when it should have warned and continued. The IndexAdapter was returning a custom error when no advisory document were found for a package. However other advisory getters such as FSGetter was propagating the **ErrNoEntries** which was then captured in the calling functions. 
We must capture that error and return the same findings given in the function call when detected an **ErrNoEntries**.
=> fix: return ErrNoEntries and capture it

pkg/cli/components/scanfindings/scanfindings.go, pkg/cli/scan.go, pkg/scan/finding.go
And deprecate the existing Advisory field, which was a pointer to the entire advisory record.
=> chore(scan): add CGAID field to Finding struct

pkg/advisory/fs_putter.go, pkg/advisory/fs_putter_test.go, pkg/advisory/testdata/fs_putter/automatic-encoder/with-config-file/.yam.yaml, pkg/advisory/testdata/fs_putter/automatic-encoder/with-config-file/_expected.yam.yaml, pkg/advisory/testdata/fs_putter/automatic-encoder/with-config-file/foo.advisories.yaml, pkg/advisory/testdata/fs_putter/automatic-encoder/with-config-file/foo_expected.advisories.yaml, pkg/advisory/testdata/fs_putter/automatic-encoder/without-config-file/foo.advisories.yaml, pkg/advisory/testdata/fs_putter/automatic-encoder/without-config-file/foo_expected.advisories.yaml
Adds a new constructor, `advisory.NewFSPutterWithAutomaticEncoder(fsys rwfs.FS)`, as an easier way to create a fully-functional `FSPutter`. This avoids having to set up the yam encoder yourself, because it's done automatically for you on a best-effort basis, reading the `.yam.yaml` file from the FS you provide.
=> feat(adv): new FSPutter constructor for automatic encode config

pkg/advisory/fs_getter.go, pkg/advisory/fs_putter.go
Today the name of the filename for put/get operation is assumed to be 1:1 for filename. It would be more flexible to be able to specify the filename separate from the packagename. The code gets tested with existing tests since the existing methods just call it by creating the same filename as before.
=> Feat: Add UpsertToFile and AdvisoriesFromFile methods to FSPutter and FSGetter respectively.

.pre-commit-hooks.yaml
To enable https://github.com/chainguard-dev/internal-dev/issues/7536, we need a .pre-commit-hooks.yaml file to tell pre-commit how to build and run the tool.
=> Add pre-commit-hook support

pkg/scan/apk.go, pkg/scan/finding.go, pkg/scan/finding_merge_test.go, pkg/scan/testdata/goldenfiles/aarch64/crane-0.14.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/crane-0.19.1-r6.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/go-1.21-1.21.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/python-3.11-3.11.1-r5.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/terraform-1.3.9-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/terraform-1.5.7-r12.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/aarch64/thanos-0.32-0.32.5-r4.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/crane-0.14.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/crane-0.19.1-r6.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/go-1.21-1.21.0-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/python-3.11-3.11.1-r5.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/terraform-1.3.9-r0.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/terraform-1.5.7-r12.apk.wolfictl-scan.json, pkg/scan/testdata/goldenfiles/x86_64/thanos-0.32-0.32.5-r4.apk.wolfictl-scan.json
Add logic to merge findings that represent the same vulnerability but are
reported under different identifiers (e.g., CVE-2023-1234 vs GHSA-xxxx).
This reduces noise in scan results when Grype reports the same vulnerability
multiple times through different matchers.
The implementation:
- Groups findings by package (name, type, location) before merging
- Identifies related findings when their ID/alias sets overlap
- Preserves the union of all aliases seen across merged findings
- Prefers findings with more complete alias data (GHSA > CVE)
This ensures that vulnerability filtering and advisory matching work
correctly by having access to all known aliases for each vulnerability,
while presenting cleaner output to users.
=> feat(scan): deduplicate vulnerability findings with different IDs

pkg/lint/rules_test.go
The assert.Equal() expects the parameters to follow the "expected, actual" order. However, the test assertions for linter rules were written in the reversed order. While doing so has no functional consequences the output was confusing.
This commit fixes that by introducing the proper order of parameters.
=> test(linter): reduce error messages ambiguity

go.mod, go.sum
to help resolve lint issues on every net new pull requests.
=> chore: bump yam to 0.2.26

pkg/lint/rules.go, pkg/lint/rules_test.go, pkg/lint/testdata/files/update-identifier-matching-git-checkout-repository-mixed-case.yaml, pkg/lint/testdata/files/update-identifier-matching-git-checkout-repository-multiple-pipelines.yaml, pkg/lint/testdata/files/update-identifier-matching-git-checkout-repository.yaml, pkg/lint/testdata/files/update-identifier-not-matching-git-checkout-repository-nolint.yaml, pkg/lint/testdata/files/update-identifier-not-matching-git-checkout-repository.yaml
The update identifier must match the github repository because, otherwise, updating the package fails. Actualy, we have had a case already where a package definition was copied & pasted from another and these values were not updated to match.
To catch any further mismatches like that this commit adds a new linter rule: update-identifier-must-match-git-repository.
It checks, in a case insensitive manner, whether the GitHub repository URL contains a GitHub identifier that matches the one from the update section of the package yaml.
Furthermore, because a single package can have multiple pipelines, this linter looks for a single match, i.e. a single repository URL from all of the pipelines that are using git-checkout must match the update identifier in order to pass.
Note that is possible to …
=> lint: add rule to make sure update identifier matches git repo

pkg/sbom/sbom.go, pkg/sbom/testdata/goldenfiles/aarch64/crane-0.19.1-r6.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/jenkins-2.461-r0.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/jruby-9.4-9.4.7.0-r0.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/openjdk-21-21.0.3-r3.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/openssl-3.3.0-r8.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/perl-yaml-syck-1.34-r3.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/php-odbc-8.2.11-r1.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/powershell-7.4.1-r0.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/py3-poetry-core-1.9.0-r1.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/python-3.11-base-3.11.9-r6.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/terraform-1.5.7-r12.apk.syft.json, pkg/sbom/testdata/goldenfiles/aarch64/thanos-0.32-0.32.5-r4.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/crane-0.19.1-r6.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/jenkins-2.461-r0.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/jruby-9.4-9.4.7.0-r0.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/openjdk-21-21.0.3-r3.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/openssl-3.3.0-r8.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/perl-yaml-syck-1.34-r3.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/php-odbc-8.2.11-r1.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/powershell-7.4.1-r0.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/py3-poetry-core-1.9.0-r1.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/python-3.11-base-3.11.9-r6.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/terraform-1.5.7-r12.apk.syft.json, pkg/sbom/testdata/goldenfiles/x86_64/thanos-0.32-0.32.5-r4.apk.syft.json
Syft logs a warning if you're using a directory source but don't set a `source.Alias` value for the source. This log message isn't warning about anything that impacts the accuracy of the analysis, but it's nonetheless noisy and annoying. This PR plugs in an alias value to avoid the warning. It also moves the Syft-to-clog wiring slightly earlier to make the effect of this change reproducible with the local CLI.
```console
$ wolfictl sbom -D ./apko-0.25.1-r2.apk > /dev/null
2025/08/26 15:55:38 WARN no explicit name and version provided for directory source, deriving artifact ID from the given path (which is not ideal)
$
```
```console
$ wolfictl sbom -D ./apko-0.25.1-r2.apk > /dev/null
$
````
=> chore(sbom): resolve warning for directory source
